// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_Loop_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        img_0_data_stream_0_V_dout,
        img_0_data_stream_0_V_empty_n,
        img_0_data_stream_0_V_read,
        img_0_data_stream_1_V_dout,
        img_0_data_stream_1_V_empty_n,
        img_0_data_stream_1_V_read,
        img_0_data_stream_2_V_dout,
        img_0_data_stream_2_V_empty_n,
        img_0_data_stream_2_V_read,
        img_1_data_stream_0_V_din,
        img_1_data_stream_0_V_full_n,
        img_1_data_stream_0_V_write,
        img_1_data_stream_1_V_din,
        img_1_data_stream_1_V_full_n,
        img_1_data_stream_1_V_write,
        img_1_data_stream_2_V_din,
        img_1_data_stream_2_V_full_n,
        img_1_data_stream_2_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st12_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv10_80 = 10'b10000000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv8_10 = 8'b10000;
parameter    ap_const_lv8_37 = 8'b110111;
parameter    ap_const_lv8_CD = 8'b11001101;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv9_3C = 9'b111100;
parameter    ap_const_lv9_22 = 9'b100010;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv13_19 = 13'b11001;
parameter    ap_const_lv22_556 = 22'b10101010110;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] rows;
input  [31:0] cols;
input  [7:0] img_0_data_stream_0_V_dout;
input   img_0_data_stream_0_V_empty_n;
output   img_0_data_stream_0_V_read;
input  [7:0] img_0_data_stream_1_V_dout;
input   img_0_data_stream_1_V_empty_n;
output   img_0_data_stream_1_V_read;
input  [7:0] img_0_data_stream_2_V_dout;
input   img_0_data_stream_2_V_empty_n;
output   img_0_data_stream_2_V_read;
output  [7:0] img_1_data_stream_0_V_din;
input   img_1_data_stream_0_V_full_n;
output   img_1_data_stream_0_V_write;
output  [7:0] img_1_data_stream_1_V_din;
input   img_1_data_stream_1_V_full_n;
output   img_1_data_stream_1_V_write;
output  [7:0] img_1_data_stream_2_V_din;
input   img_1_data_stream_2_V_full_n;
output   img_1_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_0_data_stream_0_V_read;
reg img_0_data_stream_1_V_read;
reg img_0_data_stream_2_V_read;
reg img_1_data_stream_0_V_write;
reg img_1_data_stream_1_V_write;
reg img_1_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [10:0] col_reg_341;
wire   [11:0] tmp_10_cast_fu_373_p1;
reg    ap_sig_bdd_65;
wire   [11:0] tmp_11_cast_fu_387_p1;
wire   [10:0] tmp_7_fu_391_p2;
wire   [10:0] tmp_8_fu_397_p2;
wire   [11:0] tmp_21_fu_403_p1;
wire   [11:0] tmp_24_fu_407_p1;
wire   [0:0] exitcond1_fu_415_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_85;
wire   [10:0] row_1_fu_420_p2;
reg   [10:0] row_1_reg_1326;
wire   [0:0] tmp_9_fu_426_p2;
reg   [0:0] tmp_9_reg_1331;
wire   [0:0] tmp_10_fu_437_p2;
reg   [0:0] tmp_10_reg_1336;
wire   [0:0] tmp_11_fu_443_p2;
reg   [0:0] tmp_11_reg_1341;
wire   [0:0] tmp_12_fu_449_p2;
reg   [0:0] tmp_12_reg_1346;
wire   [0:0] exitcond_fu_454_p2;
reg   [0:0] exitcond_reg_1351;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_107;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] or_cond_reg_1360;
reg    ap_sig_bdd_124;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] or_cond2_reg_1410;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it7;
reg    ap_sig_bdd_152;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1351_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1351_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1351_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1351_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1351_pp0_it5;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1351_pp0_it6;
wire   [10:0] col_1_fu_459_p2;
wire   [0:0] or_cond_fu_474_p2;
reg   [10:0] line_buffer_1_0_val_addr_reg_1364;
reg   [10:0] line_buffer_1_1_val_addr_reg_1370;
reg   [10:0] line_buffer_1_2_val_addr_reg_1376;
reg   [10:0] line_buffer_0_0_val_addr_reg_1382;
reg   [10:0] ap_reg_ppstg_line_buffer_0_0_val_addr_reg_1382_pp0_it1;
reg   [10:0] line_buffer_0_1_val_addr_reg_1388;
reg   [10:0] ap_reg_ppstg_line_buffer_0_1_val_addr_reg_1388_pp0_it1;
reg   [10:0] line_buffer_0_2_val_addr_reg_1394;
reg   [10:0] ap_reg_ppstg_line_buffer_0_2_val_addr_reg_1394_pp0_it1;
wire   [0:0] tmp11_fu_506_p2;
reg   [0:0] tmp11_reg_1400;
wire   [0:0] tmp12_fu_511_p2;
reg   [0:0] tmp12_reg_1405;
wire   [0:0] or_cond2_fu_522_p2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1410_pp0_it6;
wire   [7:0] line_buffer_1_0_val_q0;
reg   [7:0] R_reg_1414;
wire   [7:0] line_buffer_1_1_val_q0;
reg   [7:0] G_reg_1419;
wire   [7:0] line_buffer_1_2_val_q0;
reg   [7:0] B_reg_1425;
wire   [9:0] tmp9_fu_554_p2;
reg   [9:0] tmp9_reg_1430;
wire   [7:0] line_buffer_0_0_val_q0;
reg   [7:0] pix_val_0_reg_1435;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1435_pp0_it2;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1435_pp0_it3;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1435_pp0_it4;
reg   [7:0] ap_reg_ppstg_pix_val_0_reg_1435_pp0_it5;
wire   [7:0] line_buffer_0_1_val_q0;
reg   [7:0] pix_val_1_reg_1442;
reg   [7:0] ap_reg_ppstg_pix_val_1_reg_1442_pp0_it2;
wire   [7:0] line_buffer_0_2_val_q0;
reg   [7:0] pix_val_2_reg_1449;
reg   [7:0] ap_reg_ppstg_pix_val_2_reg_1449_pp0_it2;
wire   [0:0] or_cond3_fu_560_p2;
reg   [0:0] or_cond3_reg_1455;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1455_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1455_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1455_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1455_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1455_pp0_it6;
reg   [7:0] G_4_reg_1459;
reg   [7:0] tmp_i_reg_1464;
wire   [9:0] tmp4_fu_653_p2;
reg   [9:0] tmp4_reg_1469;
wire   [14:0] tmp_6_i2_fu_701_p2;
reg   [14:0] tmp_6_i2_reg_1474;
wire   [12:0] grp_fu_1203_p3;
reg   [12:0] tmp10_reg_1479;
reg   [7:0] y_window_2_1_1_reg_1484;
reg   [7:0] ap_reg_ppstg_y_window_2_1_1_reg_1484_pp0_it4;
wire   [7:0] y_fu_710_p2;
reg   [7:0] y_reg_1490;
reg   [7:0] tmp_i1_reg_1495;
wire   [7:0] y_2_fu_820_p2;
reg   [7:0] y_2_reg_1500;
wire   [8:0] tmp_2_i3_fu_832_p2;
reg   [8:0] tmp_2_i3_reg_1506;
reg   [8:0] ap_reg_ppstg_tmp_2_i3_reg_1506_pp0_it4;
reg   [8:0] ap_reg_ppstg_tmp_2_i3_reg_1506_pp0_it5;
wire  signed [10:0] x_weight_2_1_2_i_fu_916_p2;
reg  signed [10:0] x_weight_2_1_2_i_reg_1511;
wire   [10:0] tmp_19_2_cast_i_fu_942_p1;
reg   [10:0] tmp_19_2_cast_i_reg_1516;
wire   [10:0] y_weight_2_2_i_fu_945_p2;
reg   [10:0] y_weight_2_2_i_reg_1521;
wire   [0:0] tmp_i_29_fu_1015_p2;
reg   [0:0] tmp_i_29_reg_1526;
wire   [7:0] tmp_28_fu_1021_p1;
reg   [7:0] tmp_28_reg_1531;
wire   [7:0] tmp_22_fu_1025_p2;
reg   [7:0] tmp_22_reg_1536;
wire   [0:0] tmp_4_i_fu_1031_p2;
reg   [0:0] tmp_4_i_reg_1541;
wire   [7:0] tmp_29_fu_1037_p1;
reg   [7:0] tmp_29_reg_1546;
wire   [7:0] tmp_25_fu_1041_p2;
reg   [7:0] tmp_25_reg_1551;
wire   [7:0] edge_weight_i_fu_1061_p2;
reg   [7:0] edge_weight_i_reg_1556;
wire   [0:0] tmp_7_i_fu_1067_p2;
reg   [0:0] tmp_7_i_reg_1561;
wire   [0:0] tmp_8_i3_fu_1073_p2;
reg   [0:0] tmp_8_i3_reg_1567;
wire   [21:0] grp_fu_1229_p3;
reg   [21:0] mul_reg_1572;
wire   [7:0] edge_val_1_fu_1107_p3;
reg   [7:0] sepia_val_0_reg_1583;
wire   [7:0] sepia_val_2_fu_1157_p3;
reg   [7:0] sepia_val_2_reg_1588;
wire   [7:0] sepia_val_1_fu_1177_p3;
reg   [7:0] sepia_val_1_reg_1593;
wire   [10:0] line_buffer_0_0_val_address0;
reg    line_buffer_0_0_val_ce0;
wire   [10:0] line_buffer_0_0_val_address1;
reg    line_buffer_0_0_val_ce1;
reg    line_buffer_0_0_val_we1;
wire   [7:0] line_buffer_0_0_val_d1;
wire   [10:0] line_buffer_0_1_val_address0;
reg    line_buffer_0_1_val_ce0;
wire   [10:0] line_buffer_0_1_val_address1;
reg    line_buffer_0_1_val_ce1;
reg    line_buffer_0_1_val_we1;
wire   [7:0] line_buffer_0_1_val_d1;
wire   [10:0] line_buffer_0_2_val_address0;
reg    line_buffer_0_2_val_ce0;
wire   [10:0] line_buffer_0_2_val_address1;
reg    line_buffer_0_2_val_ce1;
reg    line_buffer_0_2_val_we1;
wire   [7:0] line_buffer_0_2_val_d1;
wire   [10:0] line_buffer_1_0_val_address0;
reg    line_buffer_1_0_val_ce0;
wire   [10:0] line_buffer_1_0_val_address1;
reg    line_buffer_1_0_val_ce1;
reg    line_buffer_1_0_val_we1;
wire   [7:0] line_buffer_1_0_val_d1;
wire   [10:0] line_buffer_1_1_val_address0;
reg    line_buffer_1_1_val_ce0;
wire   [10:0] line_buffer_1_1_val_address1;
reg    line_buffer_1_1_val_ce1;
reg    line_buffer_1_1_val_we1;
wire   [7:0] line_buffer_1_1_val_d1;
wire   [10:0] line_buffer_1_2_val_address0;
reg    line_buffer_1_2_val_ce0;
wire   [10:0] line_buffer_1_2_val_address1;
reg    line_buffer_1_2_val_ce1;
reg    line_buffer_1_2_val_we1;
wire   [7:0] line_buffer_1_2_val_d1;
reg   [10:0] row_reg_330;
reg    ap_sig_cseq_ST_st12_fsm_3;
reg    ap_sig_bdd_390;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it7;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it8;
wire   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it1;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it2;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it3;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it4;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it5;
reg   [7:0] ap_reg_phiprechg_edge_val1_reg_352pp0_it6;
wire   [63:0] tmp_16_fu_479_p1;
reg   [7:0] y_window_0_1_fu_132;
reg   [7:0] y_window_0_2_fu_136;
reg   [7:0] y_window_2_2_fu_140;
reg   [7:0] y_window_1_1_fu_144;
wire   [7:0] y_1_fu_843_p2;
reg   [7:0] y_window_1_2_fu_148;
reg   [7:0] y_window_2_1_fu_152;
reg   [7:0] B_1_fu_156;
reg   [7:0] G_1_fu_160;
reg   [7:0] R_1_fu_164;
wire   [10:0] tmp_1_fu_363_p1;
wire  signed [10:0] tmp_s_fu_367_p2;
wire   [10:0] tmp_2_fu_377_p1;
wire  signed [10:0] tmp_6_fu_381_p2;
wire   [11:0] row_cast_fu_411_p1;
wire  signed [11:0] output_row_fu_431_p2;
wire   [11:0] col_cast_fu_465_p1;
wire   [0:0] tmp_14_fu_469_p2;
wire  signed [11:0] output_col_fu_489_p2;
wire   [0:0] tmp_17_fu_495_p2;
wire   [0:0] tmp_18_fu_501_p2;
wire   [0:0] tmp_19_fu_516_p2;
wire   [8:0] p_shl2_i_fu_542_p3;
wire   [9:0] p_shl2_cast_i_cast_fu_550_p1;
wire   [13:0] p_shl1_i_fu_576_p3;
wire   [14:0] p_shl_i_fu_590_p3;
wire   [14:0] p_shl1_cast_i_fu_583_p1;
wire   [14:0] tmp58_cast_fu_604_p1;
wire   [14:0] tmp_6_i_fu_607_p2;
wire   [15:0] tmp_6_cast_i_fu_613_p1;
wire   [15:0] p_shl_cast_i_fu_597_p1;
wire   [12:0] grp_fu_1220_p3;
wire   [15:0] tmp2_fu_617_p2;
wire   [15:0] tmp60_cast_fu_623_p1;
wire   [15:0] tmp_8_i_fu_626_p2;
wire   [8:0] p_shl2_i6_fu_642_p3;
wire   [9:0] p_shl2_cast_i7_cast_fu_649_p1;
wire   [13:0] p_shl1_i1_fu_659_p3;
wire   [8:0] p_shl2_i1_fu_671_p3;
wire   [9:0] p_shl2_cast_i29_cast_fu_679_p1;
wire   [9:0] tmp7_fu_691_p2;
wire   [14:0] p_shl1_cast_i1_fu_667_p1;
wire   [14:0] tmp64_cast_fu_697_p1;
wire   [13:0] p_shl1_i4_fu_715_p3;
wire   [14:0] p_shl_i1_fu_729_p3;
wire   [14:0] p_shl1_cast_i5_fu_722_p1;
wire   [14:0] tmp61_cast_fu_743_p1;
wire   [14:0] tmp_6_i1_fu_746_p2;
wire   [15:0] tmp_6_cast_i1_fu_752_p1;
wire   [15:0] p_shl_cast_i1_fu_736_p1;
wire   [12:0] grp_fu_1211_p3;
wire   [15:0] tmp5_fu_756_p2;
wire   [15:0] tmp63_cast_fu_762_p1;
wire   [15:0] tmp_8_i1_fu_765_p2;
wire   [14:0] p_shl_i2_fu_781_p3;
wire   [15:0] tmp_6_cast_i2_fu_792_p1;
wire   [15:0] p_shl_cast_i2_fu_788_p1;
wire   [15:0] tmp8_fu_795_p2;
wire   [15:0] tmp66_cast_fu_801_p1;
wire   [15:0] tmp_8_i2_fu_804_p2;
wire   [7:0] tmp_i2_fu_810_p4;
wire   [8:0] tmp_cast_i2_fu_826_p1;
wire   [8:0] tmp_cast_i_fu_829_p1;
wire   [8:0] tmp_23_0_1_i_fu_860_p3;
wire   [8:0] tmp_19_0_2_cast1_i_cast_fu_872_p1;
wire   [8:0] tmp_19_0_cast2_i_cast_fu_857_p1;
wire   [8:0] x_weight_2_0_2_i_fu_876_p2;
wire   [8:0] p_shl8_i_fu_886_p3;
wire  signed [10:0] x_weight_2_0_2_cast_i_fu_882_p1;
wire   [10:0] p_shl8_cast_i_fu_894_p1;
wire   [8:0] tmp_21_1_2_i_fu_904_p3;
wire   [10:0] tmp_21_1_2_cast_i_fu_912_p1;
wire  signed [10:0] x_weight_2_1_1_i_fu_898_p2;
wire   [8:0] tmp13_fu_922_p2;
wire   [9:0] tmp_23_0_1_cast_i_fu_868_p1;
wire   [9:0] tmp69_cast_fu_928_p1;
wire   [9:0] y_weight_2_1_2_i_fu_932_p2;
wire   [10:0] y_weight_2_1_2_cast_i_fu_938_p1;
wire   [8:0] p_shl_i3_fu_983_p3;
wire   [10:0] p_shl_cast_i3_fu_990_p1;
wire   [10:0] tmp_19_2_2_cast_i_fu_999_p1;
wire  signed [10:0] x_weight_2_2_i_fu_979_p2;
wire   [10:0] y_weight_2_2_1_i_fu_994_p2;
wire  signed [10:0] x_weight_2_2_2_i_fu_1003_p2;
wire   [10:0] y_weight_2_2_2_i_fu_1009_p2;
wire   [7:0] tmp_23_fu_1051_p3;
wire   [7:0] tmp_26_fu_1056_p3;
wire   [0:0] not_tmp_7_i_fu_1090_p2;
wire   [0:0] tmp_27_fu_1103_p2;
wire   [7:0] p_i_cast_fu_1095_p3;
wire   [7:0] edge_val_fu_1085_p2;
wire   [8:0] B_cast_i_fu_1115_p4;
wire   [8:0] R_3_fu_1124_p2;
wire   [0:0] tmp_30_fu_1145_p3;
wire   [7:0] tmp_31_fu_1153_p1;
wire   [8:0] G_3_fu_1130_p2;
wire   [0:0] tmp_32_fu_1165_p3;
wire   [7:0] tmp_33_fu_1173_p1;
wire   [7:0] grp_fu_1203_p0;
wire   [5:0] grp_fu_1203_p1;
wire   [7:0] grp_fu_1203_p2;
wire   [7:0] grp_fu_1211_p0;
wire   [5:0] grp_fu_1211_p1;
wire   [7:0] grp_fu_1211_p2;
wire   [7:0] grp_fu_1220_p0;
wire   [5:0] grp_fu_1220_p1;
wire   [7:0] grp_fu_1220_p2;
wire   [7:0] grp_fu_1229_p0;
wire   [8:0] grp_fu_1229_p1;
wire   [11:0] grp_fu_1229_p2;
reg   [3:0] ap_NS_fsm;
wire   [12:0] grp_fu_1203_p00;
wire   [12:0] grp_fu_1203_p20;
wire   [12:0] grp_fu_1211_p00;
wire   [12:0] grp_fu_1211_p20;
wire   [12:0] grp_fu_1220_p00;
wire   [12:0] grp_fu_1220_p20;
wire   [9:0] grp_fu_1229_p00;
wire   [9:0] grp_fu_1229_p10;
reg    ap_sig_bdd_416;
reg    ap_sig_bdd_405;
reg    ap_sig_bdd_309;
reg    ap_sig_bdd_397;


image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_0_0_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_0_0_val_address0 ),
    .ce0( line_buffer_0_0_val_ce0 ),
    .q0( line_buffer_0_0_val_q0 ),
    .address1( line_buffer_0_0_val_address1 ),
    .ce1( line_buffer_0_0_val_ce1 ),
    .we1( line_buffer_0_0_val_we1 ),
    .d1( line_buffer_0_0_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_0_1_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_0_1_val_address0 ),
    .ce0( line_buffer_0_1_val_ce0 ),
    .q0( line_buffer_0_1_val_q0 ),
    .address1( line_buffer_0_1_val_address1 ),
    .ce1( line_buffer_0_1_val_ce1 ),
    .we1( line_buffer_0_1_val_we1 ),
    .d1( line_buffer_0_1_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_0_2_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_0_2_val_address0 ),
    .ce0( line_buffer_0_2_val_ce0 ),
    .q0( line_buffer_0_2_val_q0 ),
    .address1( line_buffer_0_2_val_address1 ),
    .ce1( line_buffer_0_2_val_ce1 ),
    .we1( line_buffer_0_2_val_we1 ),
    .d1( line_buffer_0_2_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_1_0_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_1_0_val_address0 ),
    .ce0( line_buffer_1_0_val_ce0 ),
    .q0( line_buffer_1_0_val_q0 ),
    .address1( line_buffer_1_0_val_address1 ),
    .ce1( line_buffer_1_0_val_ce1 ),
    .we1( line_buffer_1_0_val_we1 ),
    .d1( line_buffer_1_0_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_1_1_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_1_1_val_address0 ),
    .ce0( line_buffer_1_1_val_ce0 ),
    .q0( line_buffer_1_1_val_q0 ),
    .address1( line_buffer_1_1_val_address1 ),
    .ce1( line_buffer_1_1_val_ce1 ),
    .we1( line_buffer_1_1_val_we1 ),
    .d1( line_buffer_1_1_val_d1 )
);

image_filter_Loop_1_proc_line_buffer_0_0_val #(
    .DataWidth( 8 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
line_buffer_1_2_val_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( line_buffer_1_2_val_address0 ),
    .ce0( line_buffer_1_2_val_ce0 ),
    .q0( line_buffer_1_2_val_q0 ),
    .address1( line_buffer_1_2_val_address1 ),
    .ce1( line_buffer_1_2_val_ce1 ),
    .we1( line_buffer_1_2_val_we1 ),
    .d1( line_buffer_1_2_val_d1 )
);

image_filter_mac_muladd_8ns_6ns_8ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
image_filter_mac_muladd_8ns_6ns_8ns_13_1_U15(
    .din0( grp_fu_1203_p0 ),
    .din1( grp_fu_1203_p1 ),
    .din2( grp_fu_1203_p2 ),
    .dout( grp_fu_1203_p3 )
);

image_filter_mac_muladd_8ns_6ns_8ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
image_filter_mac_muladd_8ns_6ns_8ns_13_1_U16(
    .din0( grp_fu_1211_p0 ),
    .din1( grp_fu_1211_p1 ),
    .din2( grp_fu_1211_p2 ),
    .dout( grp_fu_1211_p3 )
);

image_filter_mac_muladd_8ns_6ns_8ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
image_filter_mac_muladd_8ns_6ns_8ns_13_1_U17(
    .din0( grp_fu_1220_p0 ),
    .din1( grp_fu_1220_p1 ),
    .din2( grp_fu_1220_p2 ),
    .dout( grp_fu_1220_p3 )
);

image_filter_am_addmul_8ns_9ns_12ns_22_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
image_filter_am_addmul_8ns_9ns_12ns_22_1_U18(
    .din0( grp_fu_1229_p0 ),
    .din1( grp_fu_1229_p1 ),
    .din2( grp_fu_1229_p2 ),
    .dout( grp_fu_1229_p3 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == exitcond_fu_454_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

/// ap_reg_ppiten_pp0_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_405) begin
        if (ap_sig_bdd_416) begin
            ap_reg_phiprechg_edge_val1_reg_352pp0_it2 <= ap_const_lv8_0;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_edge_val1_reg_352pp0_it2 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_397) begin
        if (ap_sig_bdd_309) begin
            ap_reg_phiprechg_edge_val1_reg_352pp0_it8 <= edge_val_1_fu_1107_p3;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_edge_val1_reg_352pp0_it8 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it7;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == exitcond_fu_454_p2))) begin
        col_reg_341 <= col_1_fu_459_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
        col_reg_341 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_3)) begin
        row_reg_330 <= row_1_reg_1326;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_65)) begin
        row_reg_330 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        B_1_fu_156 <= img_0_data_stream_2_V_dout;
        G_1_fu_160 <= img_0_data_stream_1_V_dout;
        R_1_fu_164 <= img_0_data_stream_0_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        B_reg_1425 <= line_buffer_1_2_val_q0;
        G_reg_1419 <= line_buffer_1_1_val_q0;
        R_reg_1414 <= line_buffer_1_0_val_q0;
        or_cond3_reg_1455 <= or_cond3_fu_560_p2;
        pix_val_0_reg_1435 <= line_buffer_0_0_val_q0;
        pix_val_1_reg_1442 <= line_buffer_0_1_val_q0;
        pix_val_2_reg_1449 <= line_buffer_0_2_val_q0;
        tmp9_reg_1430[9 : 1] <= tmp9_fu_554_p2[9 : 1];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it1))) begin
        G_4_reg_1459 <= G_1_fu_160;
        tmp10_reg_1479 <= grp_fu_1203_p3;
        tmp4_reg_1469[9 : 1] <= tmp4_fu_653_p2[9 : 1];
        tmp_6_i2_reg_1474[14 : 1] <= tmp_6_i2_fu_701_p2[14 : 1];
        tmp_i_reg_1464 <= {{tmp_8_i_fu_626_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_phiprechg_edge_val1_reg_352pp0_it3 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_phiprechg_edge_val1_reg_352pp0_it4 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_phiprechg_edge_val1_reg_352pp0_it5 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_phiprechg_edge_val1_reg_352pp0_it6 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_phiprechg_edge_val1_reg_352pp0_it7 <= ap_reg_phiprechg_edge_val1_reg_352pp0_it6;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_ppstg_exitcond_reg_1351_pp0_it1 <= exitcond_reg_1351;
        ap_reg_ppstg_line_buffer_0_0_val_addr_reg_1382_pp0_it1 <= line_buffer_0_0_val_addr_reg_1382;
        ap_reg_ppstg_line_buffer_0_1_val_addr_reg_1388_pp0_it1 <= line_buffer_0_1_val_addr_reg_1388;
        ap_reg_ppstg_line_buffer_0_2_val_addr_reg_1394_pp0_it1 <= line_buffer_0_2_val_addr_reg_1394;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it1 <= or_cond2_reg_1410;
        exitcond_reg_1351 <= exitcond_fu_454_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
        ap_reg_ppstg_exitcond_reg_1351_pp0_it2 <= ap_reg_ppstg_exitcond_reg_1351_pp0_it1;
        ap_reg_ppstg_exitcond_reg_1351_pp0_it3 <= ap_reg_ppstg_exitcond_reg_1351_pp0_it2;
        ap_reg_ppstg_exitcond_reg_1351_pp0_it4 <= ap_reg_ppstg_exitcond_reg_1351_pp0_it3;
        ap_reg_ppstg_exitcond_reg_1351_pp0_it5 <= ap_reg_ppstg_exitcond_reg_1351_pp0_it4;
        ap_reg_ppstg_exitcond_reg_1351_pp0_it6 <= ap_reg_ppstg_exitcond_reg_1351_pp0_it5;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it2 <= ap_reg_ppstg_or_cond2_reg_1410_pp0_it1;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it3 <= ap_reg_ppstg_or_cond2_reg_1410_pp0_it2;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it4 <= ap_reg_ppstg_or_cond2_reg_1410_pp0_it3;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it5 <= ap_reg_ppstg_or_cond2_reg_1410_pp0_it4;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it6 <= ap_reg_ppstg_or_cond2_reg_1410_pp0_it5;
        ap_reg_ppstg_or_cond2_reg_1410_pp0_it7 <= ap_reg_ppstg_or_cond2_reg_1410_pp0_it6;
        ap_reg_ppstg_or_cond3_reg_1455_pp0_it2 <= or_cond3_reg_1455;
        ap_reg_ppstg_or_cond3_reg_1455_pp0_it3 <= ap_reg_ppstg_or_cond3_reg_1455_pp0_it2;
        ap_reg_ppstg_or_cond3_reg_1455_pp0_it4 <= ap_reg_ppstg_or_cond3_reg_1455_pp0_it3;
        ap_reg_ppstg_or_cond3_reg_1455_pp0_it5 <= ap_reg_ppstg_or_cond3_reg_1455_pp0_it4;
        ap_reg_ppstg_or_cond3_reg_1455_pp0_it6 <= ap_reg_ppstg_or_cond3_reg_1455_pp0_it5;
        ap_reg_ppstg_pix_val_0_reg_1435_pp0_it2 <= pix_val_0_reg_1435;
        ap_reg_ppstg_pix_val_0_reg_1435_pp0_it3 <= ap_reg_ppstg_pix_val_0_reg_1435_pp0_it2;
        ap_reg_ppstg_pix_val_0_reg_1435_pp0_it4 <= ap_reg_ppstg_pix_val_0_reg_1435_pp0_it3;
        ap_reg_ppstg_pix_val_0_reg_1435_pp0_it5 <= ap_reg_ppstg_pix_val_0_reg_1435_pp0_it4;
        ap_reg_ppstg_pix_val_1_reg_1442_pp0_it2 <= pix_val_1_reg_1442;
        ap_reg_ppstg_pix_val_2_reg_1449_pp0_it2 <= pix_val_2_reg_1449;
        ap_reg_ppstg_tmp_2_i3_reg_1506_pp0_it4 <= tmp_2_i3_reg_1506;
        ap_reg_ppstg_tmp_2_i3_reg_1506_pp0_it5 <= ap_reg_ppstg_tmp_2_i3_reg_1506_pp0_it4;
        ap_reg_ppstg_y_window_2_1_1_reg_1484_pp0_it4 <= y_window_2_1_1_reg_1484;
        mul_reg_1572 <= grp_fu_1229_p3;
        sepia_val_0_reg_1583 <= {{mul_reg_1572[ap_const_lv32_13 : ap_const_lv32_C]}};
        sepia_val_1_reg_1593 <= sepia_val_1_fu_1177_p3;
        sepia_val_2_reg_1588 <= sepia_val_2_fu_1157_p3;
        y_window_2_1_1_reg_1484 <= y_window_2_1_fu_152;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it5) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1455_pp0_it5))) begin
        edge_weight_i_reg_1556 <= edge_weight_i_fu_1061_p2;
        tmp_7_i_reg_1561 <= tmp_7_i_fu_1067_p2;
        tmp_8_i3_reg_1567 <= tmp_8_i3_fu_1073_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == exitcond_fu_454_p2))) begin
        line_buffer_0_0_val_addr_reg_1382 <= tmp_16_fu_479_p1;
        line_buffer_0_1_val_addr_reg_1388 <= tmp_16_fu_479_p1;
        line_buffer_0_2_val_addr_reg_1394 <= tmp_16_fu_479_p1;
        line_buffer_1_0_val_addr_reg_1364 <= tmp_16_fu_479_p1;
        line_buffer_1_1_val_addr_reg_1370 <= tmp_16_fu_479_p1;
        line_buffer_1_2_val_addr_reg_1376 <= tmp_16_fu_479_p1;
        or_cond2_reg_1410 <= or_cond2_fu_522_p2;
        or_cond_reg_1360 <= or_cond_fu_474_p2;
        tmp11_reg_1400 <= tmp11_fu_506_p2;
        tmp12_reg_1405 <= tmp12_fu_511_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        row_1_reg_1326 <= row_1_fu_420_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
        tmp_10_reg_1336 <= tmp_10_fu_437_p2;
        tmp_11_reg_1341 <= tmp_11_fu_443_p2;
        tmp_12_reg_1346 <= tmp_12_fu_449_p2;
        tmp_9_reg_1331 <= tmp_9_fu_426_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it3) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1455_pp0_it3))) begin
        tmp_19_2_cast_i_reg_1516[7 : 0] <= tmp_19_2_cast_i_fu_942_p1[7 : 0];
        x_weight_2_1_2_i_reg_1511 <= x_weight_2_1_2_i_fu_916_p2;
        y_weight_2_2_i_reg_1521 <= y_weight_2_2_i_fu_945_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1455_pp0_it4))) begin
        tmp_22_reg_1536 <= tmp_22_fu_1025_p2;
        tmp_25_reg_1551 <= tmp_25_fu_1041_p2;
        tmp_28_reg_1531 <= tmp_28_fu_1021_p1;
        tmp_29_reg_1546 <= tmp_29_fu_1037_p1;
        tmp_4_i_reg_1541 <= tmp_4_i_fu_1031_p2;
        tmp_i_29_reg_1526 <= tmp_i_29_fu_1015_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it2))) begin
        tmp_2_i3_reg_1506 <= tmp_2_i3_fu_832_p2;
        tmp_i1_reg_1495 <= {{tmp_8_i1_fu_765_p2[ap_const_lv32_F : ap_const_lv32_8]}};
        y_2_reg_1500 <= y_2_fu_820_p2;
        y_reg_1490 <= y_fu_710_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it3))) begin
        y_window_0_1_fu_132 <= y_2_reg_1500;
        y_window_0_2_fu_136 <= y_window_0_1_fu_132;
        y_window_1_1_fu_144 <= y_1_fu_843_p2;
        y_window_1_2_fu_148 <= y_window_1_1_fu_144;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it2))) begin
        y_window_2_1_fu_152 <= y_fu_710_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it4))) begin
        y_window_2_2_fu_140 <= ap_reg_ppstg_y_window_2_1_1_reg_1484_pp0_it4;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or exitcond1_fu_415_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_415_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (exitcond1_fu_415_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond1_fu_415_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_107)
begin
    if (ap_sig_bdd_107) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_3 assign process. ///
always @ (ap_sig_bdd_390)
begin
    if (ap_sig_bdd_390) begin
        ap_sig_cseq_ST_st12_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_23)
begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_85)
begin
    if (ap_sig_bdd_85) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// img_0_data_stream_0_V_read assign process. ///
always @ (exitcond_reg_1351 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or or_cond_reg_1360 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        img_0_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_1_V_read assign process. ///
always @ (exitcond_reg_1351 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or or_cond_reg_1360 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        img_0_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_2_V_read assign process. ///
always @ (exitcond_reg_1351 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or or_cond_reg_1360 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        img_0_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_2_V_read = ap_const_logic_0;
    end
end

/// img_1_data_stream_0_V_write assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1410_pp0_it7 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1410_pp0_it7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        img_1_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        img_1_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// img_1_data_stream_1_V_write assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1410_pp0_it7 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1410_pp0_it7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        img_1_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        img_1_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// img_1_data_stream_2_V_write assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1410_pp0_it7 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1410_pp0_it7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        img_1_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        img_1_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// line_buffer_0_0_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_0_0_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_0_0_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_0_0_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_0_0_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_0_0_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_0_0_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_exitcond_reg_1351_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it1))) begin
        line_buffer_0_0_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_0_0_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_0_1_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_0_1_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_0_1_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_0_1_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_0_1_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_0_1_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_0_1_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_exitcond_reg_1351_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it1))) begin
        line_buffer_0_1_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_0_1_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_0_2_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_0_2_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_0_2_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_0_2_val_ce1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_0_2_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_0_2_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_0_2_val_we1 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_exitcond_reg_1351_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it1))) begin
        line_buffer_0_2_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_0_2_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_1_0_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_0_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_1_0_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_1_0_val_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_0_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_1_0_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_1_0_val_we1 assign process. ///
always @ (exitcond_reg_1351 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_0_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_1_0_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_1_1_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_1_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_1_1_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_1_1_val_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_1_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_1_1_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_1_1_val_we1 assign process. ///
always @ (exitcond_reg_1351 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_1_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_1_1_val_we1 = ap_const_logic_0;
    end
end

/// line_buffer_1_2_val_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_2_val_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_1_2_val_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_1_2_val_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_2_val_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_1_2_val_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_1_2_val_we1 assign process. ///
always @ (exitcond_reg_1351 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_reg_1351) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        line_buffer_1_2_val_we1 = ap_const_logic_1;
    end else begin
        line_buffer_1_2_val_we1 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_65 or exitcond1_fu_415_p2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it7 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_65) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond1_fu_415_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it7)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it7)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_st12_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st12_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_cast_i_fu_1115_p4 = {{mul_reg_1572[ap_const_lv32_14 : ap_const_lv32_C]}};
assign G_3_fu_1130_p2 = (ap_const_lv9_22 + B_cast_i_fu_1115_p4);
assign R_3_fu_1124_p2 = (ap_const_lv9_3C + B_cast_i_fu_1115_p4);
assign ap_reg_phiprechg_edge_val1_reg_352pp0_it1 = 'bx;

/// ap_sig_bdd_107 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_107 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_124 assign process. ///
always @ (img_0_data_stream_0_V_empty_n or img_0_data_stream_1_V_empty_n or img_0_data_stream_2_V_empty_n or exitcond_reg_1351 or or_cond_reg_1360)
begin
    ap_sig_bdd_124 = (((img_0_data_stream_0_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360)) | ((ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360) & (img_0_data_stream_1_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond_reg_1360) & (img_0_data_stream_2_V_empty_n == ap_const_logic_0)));
end

/// ap_sig_bdd_152 assign process. ///
always @ (img_1_data_stream_0_V_full_n or img_1_data_stream_1_V_full_n or img_1_data_stream_2_V_full_n or ap_reg_ppstg_or_cond2_reg_1410_pp0_it7)
begin
    ap_sig_bdd_152 = (((img_1_data_stream_0_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1410_pp0_it7)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1410_pp0_it7) & (img_1_data_stream_1_V_full_n == ap_const_logic_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1410_pp0_it7) & (img_1_data_stream_2_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_309 assign process. ///
always @ (ap_reg_ppstg_exitcond_reg_1351_pp0_it6 or ap_reg_ppstg_or_cond3_reg_1455_pp0_it6)
begin
    ap_sig_bdd_309 = ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1351_pp0_it6) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1455_pp0_it6));
end

/// ap_sig_bdd_390 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_390 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_397 assign process. ///
always @ (ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it7 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    ap_sig_bdd_397 = ((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))));
end

/// ap_sig_bdd_405 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_124 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_152 or ap_reg_ppiten_pp0_it8)
begin
    ap_sig_bdd_405 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_124 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_152 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))));
end

/// ap_sig_bdd_416 assign process. ///
always @ (exitcond_reg_1351 or or_cond3_fu_560_p2)
begin
    ap_sig_bdd_416 = ((ap_const_lv1_0 == exitcond_reg_1351) & ~(ap_const_lv1_0 == or_cond3_fu_560_p2));
end

/// ap_sig_bdd_65 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_65 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_85 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_85 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign col_1_fu_459_p2 = (col_reg_341 + ap_const_lv11_1);
assign col_cast_fu_465_p1 = col_reg_341;
assign edge_val_1_fu_1107_p3 = ((tmp_27_fu_1103_p2[0:0]===1'b1)? p_i_cast_fu_1095_p3: edge_val_fu_1085_p2);
assign edge_val_fu_1085_p2 = (edge_weight_i_reg_1556 ^ ap_const_lv8_FF);
assign edge_weight_i_fu_1061_p2 = (tmp_23_fu_1051_p3 + tmp_26_fu_1056_p3);
assign exitcond1_fu_415_p2 = (row_reg_330 == tmp_8_fu_397_p2? 1'b1: 1'b0);
assign exitcond_fu_454_p2 = (col_reg_341 == tmp_7_fu_391_p2? 1'b1: 1'b0);
assign grp_fu_1203_p0 = grp_fu_1203_p00;
assign grp_fu_1203_p00 = B_1_fu_156;
assign grp_fu_1203_p1 = ap_const_lv13_19;
assign grp_fu_1203_p2 = grp_fu_1203_p20;
assign grp_fu_1203_p20 = G_1_fu_160;
assign grp_fu_1211_p0 = grp_fu_1211_p00;
assign grp_fu_1211_p00 = ap_reg_ppstg_pix_val_2_reg_1449_pp0_it2;
assign grp_fu_1211_p1 = ap_const_lv13_19;
assign grp_fu_1211_p2 = grp_fu_1211_p20;
assign grp_fu_1211_p20 = ap_reg_ppstg_pix_val_1_reg_1442_pp0_it2;
assign grp_fu_1220_p0 = grp_fu_1220_p00;
assign grp_fu_1220_p00 = B_reg_1425;
assign grp_fu_1220_p1 = ap_const_lv13_19;
assign grp_fu_1220_p2 = grp_fu_1220_p20;
assign grp_fu_1220_p20 = G_reg_1419;
assign grp_fu_1229_p0 = grp_fu_1229_p00;
assign grp_fu_1229_p00 = ap_reg_ppstg_pix_val_0_reg_1435_pp0_it5;
assign grp_fu_1229_p1 = grp_fu_1229_p10;
assign grp_fu_1229_p10 = ap_reg_ppstg_tmp_2_i3_reg_1506_pp0_it5;
assign grp_fu_1229_p2 = ap_const_lv22_556;
assign img_1_data_stream_0_V_din = (ap_reg_phiprechg_edge_val1_reg_352pp0_it8 + sepia_val_0_reg_1583);
assign img_1_data_stream_1_V_din = (ap_reg_phiprechg_edge_val1_reg_352pp0_it8 + sepia_val_1_reg_1593);
assign img_1_data_stream_2_V_din = (ap_reg_phiprechg_edge_val1_reg_352pp0_it8 + sepia_val_2_reg_1588);
assign line_buffer_0_0_val_address0 = tmp_16_fu_479_p1;
assign line_buffer_0_0_val_address1 = ap_reg_ppstg_line_buffer_0_0_val_addr_reg_1382_pp0_it1;
assign line_buffer_0_0_val_d1 = R_1_fu_164;
assign line_buffer_0_1_val_address0 = tmp_16_fu_479_p1;
assign line_buffer_0_1_val_address1 = ap_reg_ppstg_line_buffer_0_1_val_addr_reg_1388_pp0_it1;
assign line_buffer_0_1_val_d1 = G_1_fu_160;
assign line_buffer_0_2_val_address0 = tmp_16_fu_479_p1;
assign line_buffer_0_2_val_address1 = ap_reg_ppstg_line_buffer_0_2_val_addr_reg_1394_pp0_it1;
assign line_buffer_0_2_val_d1 = B_1_fu_156;
assign line_buffer_1_0_val_address0 = tmp_16_fu_479_p1;
assign line_buffer_1_0_val_address1 = line_buffer_1_0_val_addr_reg_1364;
assign line_buffer_1_0_val_d1 = line_buffer_0_0_val_q0;
assign line_buffer_1_1_val_address0 = tmp_16_fu_479_p1;
assign line_buffer_1_1_val_address1 = line_buffer_1_1_val_addr_reg_1370;
assign line_buffer_1_1_val_d1 = line_buffer_0_1_val_q0;
assign line_buffer_1_2_val_address0 = tmp_16_fu_479_p1;
assign line_buffer_1_2_val_address1 = line_buffer_1_2_val_addr_reg_1376;
assign line_buffer_1_2_val_d1 = line_buffer_0_2_val_q0;
assign not_tmp_7_i_fu_1090_p2 = (tmp_7_i_reg_1561 ^ ap_const_lv1_1);
assign or_cond2_fu_522_p2 = (tmp_11_reg_1341 & tmp_19_fu_516_p2);
assign or_cond3_fu_560_p2 = (tmp12_reg_1405 | tmp11_reg_1400);
assign or_cond_fu_474_p2 = (tmp_9_reg_1331 & tmp_14_fu_469_p2);
assign output_col_fu_489_p2 = ($signed(col_cast_fu_465_p1) + $signed(ap_const_lv12_FFF));
assign output_row_fu_431_p2 = ($signed(row_cast_fu_411_p1) + $signed(ap_const_lv12_FFF));
assign p_i_cast_fu_1095_p3 = ((not_tmp_7_i_fu_1090_p2[0:0]===1'b1)? ap_const_lv8_FF: ap_const_lv8_0);
assign p_shl1_cast_i1_fu_667_p1 = p_shl1_i1_fu_659_p3;
assign p_shl1_cast_i5_fu_722_p1 = p_shl1_i4_fu_715_p3;
assign p_shl1_cast_i_fu_583_p1 = p_shl1_i_fu_576_p3;
assign p_shl1_i1_fu_659_p3 = {{R_1_fu_164}, {ap_const_lv6_0}};
assign p_shl1_i4_fu_715_p3 = {{ap_reg_ppstg_pix_val_0_reg_1435_pp0_it2}, {ap_const_lv6_0}};
assign p_shl1_i_fu_576_p3 = {{R_reg_1414}, {ap_const_lv6_0}};
assign p_shl2_cast_i29_cast_fu_679_p1 = p_shl2_i1_fu_671_p3;
assign p_shl2_cast_i7_cast_fu_649_p1 = p_shl2_i6_fu_642_p3;
assign p_shl2_cast_i_cast_fu_550_p1 = p_shl2_i_fu_542_p3;
assign p_shl2_i1_fu_671_p3 = {{R_1_fu_164}, {ap_const_lv1_0}};
assign p_shl2_i6_fu_642_p3 = {{pix_val_0_reg_1435}, {ap_const_lv1_0}};
assign p_shl2_i_fu_542_p3 = {{line_buffer_1_0_val_q0}, {ap_const_lv1_0}};
assign p_shl8_cast_i_fu_894_p1 = p_shl8_i_fu_886_p3;
assign p_shl8_i_fu_886_p3 = {{y_1_fu_843_p2}, {ap_const_lv1_0}};
assign p_shl_cast_i1_fu_736_p1 = p_shl_i1_fu_729_p3;
assign p_shl_cast_i2_fu_788_p1 = p_shl_i2_fu_781_p3;
assign p_shl_cast_i3_fu_990_p1 = p_shl_i3_fu_983_p3;
assign p_shl_cast_i_fu_597_p1 = p_shl_i_fu_590_p3;
assign p_shl_i1_fu_729_p3 = {{ap_reg_ppstg_pix_val_1_reg_1442_pp0_it2}, {ap_const_lv7_0}};
assign p_shl_i2_fu_781_p3 = {{G_4_reg_1459}, {ap_const_lv7_0}};
assign p_shl_i3_fu_983_p3 = {{ap_reg_ppstg_y_window_2_1_1_reg_1484_pp0_it4}, {ap_const_lv1_0}};
assign p_shl_i_fu_590_p3 = {{G_reg_1419}, {ap_const_lv7_0}};
assign row_1_fu_420_p2 = (row_reg_330 + ap_const_lv11_1);
assign row_cast_fu_411_p1 = row_reg_330;
assign sepia_val_1_fu_1177_p3 = ((tmp_32_fu_1165_p3[0:0]===1'b1)? ap_const_lv8_FF: tmp_33_fu_1173_p1);
assign sepia_val_2_fu_1157_p3 = ((tmp_30_fu_1145_p3[0:0]===1'b1)? ap_const_lv8_FF: tmp_31_fu_1153_p1);
assign tmp11_fu_506_p2 = (tmp_10_reg_1336 | tmp_17_fu_495_p2);
assign tmp12_fu_511_p2 = (tmp_12_reg_1346 | tmp_18_fu_501_p2);
assign tmp13_fu_922_p2 = (tmp_19_0_2_cast1_i_cast_fu_872_p1 + tmp_19_0_cast2_i_cast_fu_857_p1);
assign tmp2_fu_617_p2 = (tmp_6_cast_i_fu_613_p1 + p_shl_cast_i_fu_597_p1);
assign tmp4_fu_653_p2 = (p_shl2_cast_i7_cast_fu_649_p1 + ap_const_lv10_80);
assign tmp58_cast_fu_604_p1 = tmp9_reg_1430;
assign tmp5_fu_756_p2 = (tmp_6_cast_i1_fu_752_p1 + p_shl_cast_i1_fu_736_p1);
assign tmp60_cast_fu_623_p1 = grp_fu_1220_p3;
assign tmp61_cast_fu_743_p1 = tmp4_reg_1469;
assign tmp63_cast_fu_762_p1 = grp_fu_1211_p3;
assign tmp64_cast_fu_697_p1 = tmp7_fu_691_p2;
assign tmp66_cast_fu_801_p1 = tmp10_reg_1479;
assign tmp69_cast_fu_928_p1 = tmp13_fu_922_p2;
assign tmp7_fu_691_p2 = (p_shl2_cast_i29_cast_fu_679_p1 + ap_const_lv10_80);
assign tmp8_fu_795_p2 = (tmp_6_cast_i2_fu_792_p1 + p_shl_cast_i2_fu_788_p1);
assign tmp9_fu_554_p2 = (p_shl2_cast_i_cast_fu_550_p1 + ap_const_lv10_80);
assign tmp_10_cast_fu_373_p1 = $unsigned(tmp_s_fu_367_p2);
assign tmp_10_fu_437_p2 = (output_row_fu_431_p2 == ap_const_lv12_0? 1'b1: 1'b0);
assign tmp_11_cast_fu_387_p1 = $unsigned(tmp_6_fu_381_p2);
assign tmp_11_fu_443_p2 = (row_reg_330 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_12_fu_449_p2 = (output_row_fu_431_p2 == tmp_10_cast_fu_373_p1? 1'b1: 1'b0);
assign tmp_14_fu_469_p2 = ($signed(col_cast_fu_465_p1) < $signed(tmp_24_fu_407_p1)? 1'b1: 1'b0);
assign tmp_16_fu_479_p1 = col_reg_341;
assign tmp_17_fu_495_p2 = (output_col_fu_489_p2 == ap_const_lv12_0? 1'b1: 1'b0);
assign tmp_18_fu_501_p2 = (output_col_fu_489_p2 == tmp_11_cast_fu_387_p1? 1'b1: 1'b0);
assign tmp_19_0_2_cast1_i_cast_fu_872_p1 = y_window_0_2_fu_136;
assign tmp_19_0_cast2_i_cast_fu_857_p1 = y_2_reg_1500;
assign tmp_19_2_2_cast_i_fu_999_p1 = y_window_2_2_fu_140;
assign tmp_19_2_cast_i_fu_942_p1 = y_reg_1490;
assign tmp_19_fu_516_p2 = (col_reg_341 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_1_fu_363_p1 = rows[10:0];
assign tmp_21_1_2_cast_i_fu_912_p1 = tmp_21_1_2_i_fu_904_p3;
assign tmp_21_1_2_i_fu_904_p3 = {{y_window_1_2_fu_148}, {ap_const_lv1_0}};
assign tmp_21_fu_403_p1 = rows[11:0];
assign tmp_22_fu_1025_p2 = (ap_const_lv8_0 - tmp_28_fu_1021_p1);
assign tmp_23_0_1_cast_i_fu_868_p1 = tmp_23_0_1_i_fu_860_p3;
assign tmp_23_0_1_i_fu_860_p3 = {{y_window_0_1_fu_132}, {ap_const_lv1_0}};
assign tmp_23_fu_1051_p3 = ((tmp_i_29_reg_1526[0:0]===1'b1)? tmp_28_reg_1531: tmp_22_reg_1536);
assign tmp_24_fu_407_p1 = cols[11:0];
assign tmp_25_fu_1041_p2 = (ap_const_lv8_0 - tmp_29_fu_1037_p1);
assign tmp_26_fu_1056_p3 = ((tmp_4_i_reg_1541[0:0]===1'b1)? tmp_29_reg_1546: tmp_25_reg_1551);
assign tmp_27_fu_1103_p2 = (tmp_7_i_reg_1561 | tmp_8_i3_reg_1567);
assign tmp_28_fu_1021_p1 = x_weight_2_2_2_i_fu_1003_p2[7:0];
assign tmp_29_fu_1037_p1 = y_weight_2_2_2_i_fu_1009_p2[7:0];
assign tmp_2_fu_377_p1 = cols[10:0];
assign tmp_2_i3_fu_832_p2 = (tmp_cast_i2_fu_826_p1 + tmp_cast_i_fu_829_p1);
assign tmp_30_fu_1145_p3 = R_3_fu_1124_p2[ap_const_lv32_8];
assign tmp_31_fu_1153_p1 = R_3_fu_1124_p2[7:0];
assign tmp_32_fu_1165_p3 = G_3_fu_1130_p2[ap_const_lv32_8];
assign tmp_33_fu_1173_p1 = G_3_fu_1130_p2[7:0];
assign tmp_4_i_fu_1031_p2 = ($signed(y_weight_2_2_2_i_fu_1009_p2) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign tmp_6_cast_i1_fu_752_p1 = tmp_6_i1_fu_746_p2;
assign tmp_6_cast_i2_fu_792_p1 = tmp_6_i2_reg_1474;
assign tmp_6_cast_i_fu_613_p1 = tmp_6_i_fu_607_p2;
assign tmp_6_fu_381_p2 = ($signed(ap_const_lv11_7FF) + $signed(tmp_2_fu_377_p1));
assign tmp_6_i1_fu_746_p2 = (p_shl1_cast_i5_fu_722_p1 + tmp61_cast_fu_743_p1);
assign tmp_6_i2_fu_701_p2 = (p_shl1_cast_i1_fu_667_p1 + tmp64_cast_fu_697_p1);
assign tmp_6_i_fu_607_p2 = (p_shl1_cast_i_fu_583_p1 + tmp58_cast_fu_604_p1);
assign tmp_7_fu_391_p2 = (ap_const_lv11_1 + tmp_2_fu_377_p1);
assign tmp_7_i_fu_1067_p2 = (edge_weight_i_fu_1061_p2 < ap_const_lv8_37? 1'b1: 1'b0);
assign tmp_8_fu_397_p2 = (ap_const_lv11_1 + tmp_1_fu_363_p1);
assign tmp_8_i1_fu_765_p2 = (tmp5_fu_756_p2 + tmp63_cast_fu_762_p1);
assign tmp_8_i2_fu_804_p2 = (tmp8_fu_795_p2 + tmp66_cast_fu_801_p1);
assign tmp_8_i3_fu_1073_p2 = (edge_weight_i_fu_1061_p2 > ap_const_lv8_CD? 1'b1: 1'b0);
assign tmp_8_i_fu_626_p2 = (tmp2_fu_617_p2 + tmp60_cast_fu_623_p1);
assign tmp_9_fu_426_p2 = ($signed(row_cast_fu_411_p1) < $signed(tmp_21_fu_403_p1)? 1'b1: 1'b0);
assign tmp_cast_i2_fu_826_p1 = ap_reg_ppstg_pix_val_2_reg_1449_pp0_it2;
assign tmp_cast_i_fu_829_p1 = ap_reg_ppstg_pix_val_1_reg_1442_pp0_it2;
assign tmp_i2_fu_810_p4 = {{tmp_8_i2_fu_804_p2[ap_const_lv32_F : ap_const_lv32_8]}};
assign tmp_i_29_fu_1015_p2 = ($signed(x_weight_2_2_2_i_fu_1003_p2) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign tmp_s_fu_367_p2 = ($signed(ap_const_lv11_7FF) + $signed(tmp_1_fu_363_p1));
assign x_weight_2_0_2_cast_i_fu_882_p1 = $signed(x_weight_2_0_2_i_fu_876_p2);
assign x_weight_2_0_2_i_fu_876_p2 = (tmp_19_0_2_cast1_i_cast_fu_872_p1 - tmp_19_0_cast2_i_cast_fu_857_p1);
assign x_weight_2_1_1_i_fu_898_p2 = ($signed(x_weight_2_0_2_cast_i_fu_882_p1) - $signed(p_shl8_cast_i_fu_894_p1));
assign x_weight_2_1_2_i_fu_916_p2 = ($signed(tmp_21_1_2_cast_i_fu_912_p1) + $signed(x_weight_2_1_1_i_fu_898_p2));
assign x_weight_2_2_2_i_fu_1003_p2 = ($signed(tmp_19_2_2_cast_i_fu_999_p1) + $signed(x_weight_2_2_i_fu_979_p2));
assign x_weight_2_2_i_fu_979_p2 = ($signed(x_weight_2_1_2_i_reg_1511) - $signed(tmp_19_2_cast_i_reg_1516));
assign y_1_fu_843_p2 = (tmp_i1_reg_1495 + ap_const_lv8_10);
assign y_2_fu_820_p2 = (tmp_i2_fu_810_p4 + ap_const_lv8_10);
assign y_fu_710_p2 = (tmp_i_reg_1464 + ap_const_lv8_10);
assign y_weight_2_1_2_cast_i_fu_938_p1 = y_weight_2_1_2_i_fu_932_p2;
assign y_weight_2_1_2_i_fu_932_p2 = (tmp_23_0_1_cast_i_fu_868_p1 + tmp69_cast_fu_928_p1);
assign y_weight_2_2_1_i_fu_994_p2 = (y_weight_2_2_i_reg_1521 - p_shl_cast_i3_fu_990_p1);
assign y_weight_2_2_2_i_fu_1009_p2 = (y_weight_2_2_1_i_fu_994_p2 - tmp_19_2_2_cast_i_fu_999_p1);
assign y_weight_2_2_i_fu_945_p2 = (y_weight_2_1_2_cast_i_fu_938_p1 - tmp_19_2_cast_i_fu_942_p1);
always @ (posedge ap_clk)
begin
    tmp9_reg_1430[0] <= 1'b0;
    tmp4_reg_1469[0] <= 1'b0;
    tmp_6_i2_reg_1474[0] <= 1'b0;
    tmp_19_2_cast_i_reg_1516[10:8] <= 3'b000;
end



endmodule //image_filter_Loop_1_proc

