// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_CvtColor (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st11_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv29_1322D0 = 29'b100110010001011010000;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv30_259168 = 30'b1001011001000101101000;
parameter    ap_const_lv28_74BC6 = 28'b1110100101111000110;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [10:0] j_reg_132;
reg    ap_sig_bdd_55;
wire   [0:0] exitcond2_fu_147_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_67;
wire   [10:0] i_1_fu_152_p2;
reg   [10:0] i_1_reg_282;
wire   [0:0] exitcond_fu_162_p2;
reg   [0:0] exitcond_reg_287;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_78;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_92;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_287_pp0_it6;
reg    ap_sig_bdd_110;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_287_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_287_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_287_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_287_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_287_pp0_it5;
wire   [10:0] j_1_fu_167_p2;
reg   [7:0] tmp_12_reg_296;
reg   [7:0] ap_reg_ppstg_tmp_12_reg_296_pp0_it2;
reg   [7:0] ap_reg_ppstg_tmp_12_reg_296_pp0_it3;
reg   [7:0] ap_reg_ppstg_tmp_12_reg_296_pp0_it4;
reg   [7:0] tmp_13_reg_301;
reg   [7:0] ap_reg_ppstg_tmp_13_reg_301_pp0_it2;
reg   [7:0] ap_reg_ppstg_tmp_13_reg_301_pp0_it3;
reg   [7:0] ap_reg_ppstg_tmp_13_reg_301_pp0_it4;
reg   [7:0] ap_reg_ppstg_tmp_13_reg_301_pp0_it5;
reg   [7:0] tmp_14_reg_306;
wire   [28:0] grp_fu_176_p2;
reg   [28:0] r_V_4_i_reg_316;
wire   [28:0] grp_fu_261_p3;
reg   [28:0] p_Val2_1_reg_321;
wire   [7:0] p_Val2_4_fu_218_p2;
reg   [7:0] p_Val2_4_reg_326;
reg   [0:0] tmp_10_reg_331;
wire   [0:0] p_Result_2_i_i_i_not_fu_232_p2;
reg   [0:0] p_Result_2_i_i_i_not_reg_336;
reg   [10:0] i_reg_121;
reg    ap_sig_cseq_ST_st11_fsm_3;
reg    ap_sig_bdd_180;
wire   [11:0] i_cast_fu_143_p1;
wire   [11:0] j_cast_fu_158_p1;
wire   [7:0] grp_fu_176_p0;
wire   [21:0] grp_fu_176_p1;
wire   [29:0] grp_fu_250_p3;
wire   [0:0] tmp_8_fu_200_p3;
wire   [7:0] p_Val2_3_fu_191_p4;
wire   [7:0] tmp_1_i_i_i_fu_207_p1;
wire   [0:0] tmp_9_fu_211_p3;
wire   [0:0] not_carry_fu_238_p2;
wire   [7:0] grp_fu_250_p0;
wire   [22:0] grp_fu_250_p1;
wire   [28:0] grp_fu_250_p2;
wire   [7:0] grp_fu_261_p0;
wire   [19:0] grp_fu_261_p1;
wire   [28:0] grp_fu_261_p2;
reg    grp_fu_176_ce;
reg   [3:0] ap_NS_fsm;
wire   [28:0] grp_fu_176_p00;
wire   [29:0] grp_fu_250_p00;
wire   [29:0] grp_fu_250_p20;
wire   [27:0] grp_fu_261_p00;


image_filter_mul_8ns_22ns_29_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 29 ))
image_filter_mul_8ns_22ns_29_3_U38(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_176_p0 ),
    .din1( grp_fu_176_p1 ),
    .ce( grp_fu_176_ce ),
    .dout( grp_fu_176_p2 )
);

image_filter_mac_muladd_8ns_23ns_29ns_30_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 23 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 30 ))
image_filter_mac_muladd_8ns_23ns_29ns_30_1_U39(
    .din0( grp_fu_250_p0 ),
    .din1( grp_fu_250_p1 ),
    .din2( grp_fu_250_p2 ),
    .dout( grp_fu_250_p3 )
);

image_filter_mac_muladd_8ns_20ns_29ns_29_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 20 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
image_filter_mac_muladd_8ns_20ns_29ns_29_1_U40(
    .din0( grp_fu_261_p0 ),
    .din1( grp_fu_261_p1 ),
    .din2( grp_fu_261_p2 ),
    .dout( grp_fu_261_p3 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_fu_147_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond_fu_162_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_fu_147_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (exitcond_fu_162_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_fu_147_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond_fu_162_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_fu_147_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_3)) begin
        i_reg_121 <= i_1_reg_282;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_55)) begin
        i_reg_121 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (exitcond_fu_162_p2 == ap_const_lv1_0))) begin
        j_reg_132 <= j_1_fu_167_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_fu_147_p2 == ap_const_lv1_0))) begin
        j_reg_132 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond_reg_287_pp0_it1 <= exitcond_reg_287;
        exitcond_reg_287 <= exitcond_fu_162_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
        ap_reg_ppstg_exitcond_reg_287_pp0_it2 <= ap_reg_ppstg_exitcond_reg_287_pp0_it1;
        ap_reg_ppstg_exitcond_reg_287_pp0_it3 <= ap_reg_ppstg_exitcond_reg_287_pp0_it2;
        ap_reg_ppstg_exitcond_reg_287_pp0_it4 <= ap_reg_ppstg_exitcond_reg_287_pp0_it3;
        ap_reg_ppstg_exitcond_reg_287_pp0_it5 <= ap_reg_ppstg_exitcond_reg_287_pp0_it4;
        ap_reg_ppstg_exitcond_reg_287_pp0_it6 <= ap_reg_ppstg_exitcond_reg_287_pp0_it5;
        ap_reg_ppstg_tmp_12_reg_296_pp0_it2 <= tmp_12_reg_296;
        ap_reg_ppstg_tmp_12_reg_296_pp0_it3 <= ap_reg_ppstg_tmp_12_reg_296_pp0_it2;
        ap_reg_ppstg_tmp_12_reg_296_pp0_it4 <= ap_reg_ppstg_tmp_12_reg_296_pp0_it3;
        ap_reg_ppstg_tmp_13_reg_301_pp0_it2 <= tmp_13_reg_301;
        ap_reg_ppstg_tmp_13_reg_301_pp0_it3 <= ap_reg_ppstg_tmp_13_reg_301_pp0_it2;
        ap_reg_ppstg_tmp_13_reg_301_pp0_it4 <= ap_reg_ppstg_tmp_13_reg_301_pp0_it3;
        ap_reg_ppstg_tmp_13_reg_301_pp0_it5 <= ap_reg_ppstg_tmp_13_reg_301_pp0_it4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_1_reg_282 <= i_1_fu_152_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_287_pp0_it5))) begin
        p_Result_2_i_i_i_not_reg_336 <= p_Result_2_i_i_i_not_fu_232_p2;
        p_Val2_4_reg_326 <= p_Val2_4_fu_218_p2;
        tmp_10_reg_331 <= p_Val2_4_fu_218_p2[ap_const_lv32_7];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_287_pp0_it4))) begin
        p_Val2_1_reg_321 <= grp_fu_261_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_287_pp0_it3))) begin
        r_V_4_i_reg_316 <= grp_fu_176_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_287 == ap_const_lv1_0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        tmp_12_reg_296 <= p_src_data_stream_0_V_dout;
        tmp_13_reg_301 <= p_src_data_stream_1_V_dout;
        tmp_14_reg_306 <= p_src_data_stream_2_V_dout;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or exitcond2_fu_147_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_fu_147_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (exitcond2_fu_147_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_fu_147_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_78)
begin
    if (ap_sig_bdd_78) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_3 assign process. ///
always @ (ap_sig_bdd_180)
begin
    if (ap_sig_bdd_180) begin
        ap_sig_cseq_ST_st11_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_23)
begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_67)
begin
    if (ap_sig_bdd_67) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// grp_fu_176_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_110 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        grp_fu_176_ce = ap_const_logic_1;
    end else begin
        grp_fu_176_ce = ap_const_logic_0;
    end
end

/// p_dst_data_stream_V_write assign process. ///
always @ (ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_287_pp0_it6 or ap_sig_bdd_110 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_287_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (exitcond_reg_287 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_110 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_287 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_1_V_read assign process. ///
always @ (exitcond_reg_287 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_110 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_287 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_2_V_read assign process. ///
always @ (exitcond_reg_287 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_110 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_287 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_55 or exitcond2_fu_147_p2 or exitcond_fu_162_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6 or ap_sig_bdd_110 or ap_reg_ppiten_pp0_it7)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_55) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond2_fu_147_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond_fu_162_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_110 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond_fu_162_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st11_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st11_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_110 assign process. ///
always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_exitcond_reg_287_pp0_it6)
begin
    ap_sig_bdd_110 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_287_pp0_it6));
end

/// ap_sig_bdd_180 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_180 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_55 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_55 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_67 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_67 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_78 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_78 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_92 assign process. ///
always @ (p_src_data_stream_0_V_empty_n or p_src_data_stream_1_V_empty_n or p_src_data_stream_2_V_empty_n or exitcond_reg_287)
begin
    ap_sig_bdd_92 = (((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond_reg_287 == ap_const_lv1_0)) | ((exitcond_reg_287 == ap_const_lv1_0) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_287 == ap_const_lv1_0) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)));
end
assign exitcond2_fu_147_p2 = (i_cast_fu_143_p1 == p_src_rows_V_read? 1'b1: 1'b0);
assign exitcond_fu_162_p2 = (j_cast_fu_158_p1 == p_src_cols_V_read? 1'b1: 1'b0);
assign grp_fu_176_p0 = grp_fu_176_p00;
assign grp_fu_176_p00 = tmp_14_reg_306;
assign grp_fu_176_p1 = ap_const_lv29_1322D0;
assign grp_fu_250_p0 = grp_fu_250_p00;
assign grp_fu_250_p00 = ap_reg_ppstg_tmp_13_reg_301_pp0_it5;
assign grp_fu_250_p1 = ap_const_lv30_259168;
assign grp_fu_250_p2 = grp_fu_250_p20;
assign grp_fu_250_p20 = p_Val2_1_reg_321;
assign grp_fu_261_p0 = grp_fu_261_p00;
assign grp_fu_261_p00 = ap_reg_ppstg_tmp_12_reg_296_pp0_it4;
assign grp_fu_261_p1 = ap_const_lv28_74BC6;
assign grp_fu_261_p2 = r_V_4_i_reg_316;
assign i_1_fu_152_p2 = (i_reg_121 + ap_const_lv11_1);
assign i_cast_fu_143_p1 = i_reg_121;
assign j_1_fu_167_p2 = (j_reg_132 + ap_const_lv11_1);
assign j_cast_fu_158_p1 = j_reg_132;
assign not_carry_fu_238_p2 = (tmp_10_reg_331 | p_Result_2_i_i_i_not_reg_336);
assign p_Result_2_i_i_i_not_fu_232_p2 = (tmp_9_fu_211_p3 ^ ap_const_lv1_1);
assign p_Val2_3_fu_191_p4 = {{grp_fu_250_p3[ap_const_lv32_1D : ap_const_lv32_16]}};
assign p_Val2_4_fu_218_p2 = (p_Val2_3_fu_191_p4 + tmp_1_i_i_i_fu_207_p1);
assign p_dst_data_stream_V_din = ((not_carry_fu_238_p2[0:0]===1'b1)? p_Val2_4_reg_326: ap_const_lv8_FF);
assign tmp_1_i_i_i_fu_207_p1 = tmp_8_fu_200_p3;
assign tmp_8_fu_200_p3 = grp_fu_250_p3[ap_const_lv32_15];
assign tmp_9_fu_211_p3 = grp_fu_250_p3[ap_const_lv32_1D];


endmodule //image_filter_CvtColor

