// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter_Loop_1_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_Loop_1_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_Loop_1_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> image_filter_Loop_1_proc::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> image_filter_Loop_1_proc::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> image_filter_Loop_1_proc::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> image_filter_Loop_1_proc::ap_ST_st7_fsm_3 = "1000";
const sc_lv<32> image_filter_Loop_1_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_Loop_1_proc::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_Loop_1_proc::ap_const_lv32_1 = "1";
const sc_lv<32> image_filter_Loop_1_proc::ap_const_lv32_2 = "10";
const sc_lv<1> image_filter_Loop_1_proc::ap_const_lv1_0 = "0";
const sc_lv<32> image_filter_Loop_1_proc::ap_const_lv32_3 = "11";
const sc_lv<11> image_filter_Loop_1_proc::ap_const_lv11_0 = "00000000000";
const sc_lv<11> image_filter_Loop_1_proc::ap_const_lv11_1 = "1";
const sc_lv<32> image_filter_Loop_1_proc::ap_const_lv32_A = "1010";
const sc_lv<10> image_filter_Loop_1_proc::ap_const_lv10_0 = "0000000000";

image_filter_Loop_1_proc::image_filter_Loop_1_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_fu_189_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_fu_189_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_100);
    sensitive << ( img_0_data_stream_0_V_empty_n );
    sensitive << ( img_0_data_stream_1_V_empty_n );
    sensitive << ( img_0_data_stream_2_V_empty_n );
    sensitive << ( exitcond1_reg_542 );

    SC_METHOD(thread_ap_sig_bdd_116);
    sensitive << ( img_1_data_stream_0_V_full_n );
    sensitive << ( img_1_data_stream_1_V_full_n );
    sensitive << ( img_1_data_stream_2_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );

    SC_METHOD(thread_ap_sig_bdd_195);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_63);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_75);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_75 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_3);
    sensitive << ( ap_sig_bdd_195 );

    SC_METHOD(thread_brmerge1_1_fu_365_p2);
    sensitive << ( c_1_reg_616 );
    sensitive << ( rev3_fu_360_p2 );

    SC_METHOD(thread_brmerge1_2_fu_423_p2);
    sensitive << ( c_2_fu_383_p2 );
    sensitive << ( rev5_fu_417_p2 );

    SC_METHOD(thread_brmerge1_fu_326_p2);
    sensitive << ( c_reg_600 );
    sensitive << ( rev1_fu_321_p2 );

    SC_METHOD(thread_brmerge_1_fu_354_p2);
    sensitive << ( rev2_fu_344_p2 );
    sensitive << ( c_0_not_1_fu_349_p2 );

    SC_METHOD(thread_brmerge_2_fu_406_p2);
    sensitive << ( rev4_fu_394_p2 );
    sensitive << ( c_0_not_2_fu_400_p2 );

    SC_METHOD(thread_brmerge_fu_315_p2);
    sensitive << ( rev_fu_305_p2 );
    sensitive << ( c_0_not_fu_310_p2 );

    SC_METHOD(thread_buffer_val_0_1_1_scl_val_0_fu_331_p3);
    sensitive << ( buffer_val_0_1_1_load_reg_564 );
    sensitive << ( scl_val_0_reg_579 );
    sensitive << ( brmerge1_fu_326_p2 );

    SC_METHOD(thread_buffer_val_1_1_1_scl_val_1_fu_370_p3);
    sensitive << ( buffer_val_1_1_1_load_reg_574 );
    sensitive << ( scl_val_1_reg_585 );
    sensitive << ( brmerge1_1_fu_365_p2 );

    SC_METHOD(thread_buffer_val_2_1_1_p_val_2_fu_438_p3);
    sensitive << ( ap_reg_ppstg_p_val_2_reg_591_pp0_it2 );
    sensitive << ( buffer_val_2_1_1_load_reg_637 );
    sensitive << ( brmerge1_2_reg_659 );

    SC_METHOD(thread_c_0_not_1_fu_349_p2);
    sensitive << ( c_1_reg_616 );

    SC_METHOD(thread_c_0_not_2_fu_400_p2);
    sensitive << ( c_2_fu_383_p2 );

    SC_METHOD(thread_c_0_not_fu_310_p2);
    sensitive << ( c_reg_600 );

    SC_METHOD(thread_c_1_fu_261_p2);
    sensitive << ( img_0_data_stream_1_V_dout );
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buffer_val_1_1_fu_88 );

    SC_METHOD(thread_c_2_fu_383_p2);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it1 );
    sensitive << ( p_val_2_reg_591 );
    sensitive << ( buffer_val_2_1_fu_96 );

    SC_METHOD(thread_c_fu_243_p2);
    sensitive << ( img_0_data_stream_0_V_dout );
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buffer_val_0_1_fu_80 );

    SC_METHOD(thread_col_1_fu_209_p2);
    sensitive << ( col_reg_166 );

    SC_METHOD(thread_col_cast_fu_200_p1);
    sensitive << ( col_reg_166 );

    SC_METHOD(thread_exitcond1_fu_204_p2);
    sensitive << ( tmp_4_fu_181_p1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( col_cast_fu_200_p1 );

    SC_METHOD(thread_exitcond2_fu_189_p2);
    sensitive << ( tmp_3_fu_177_p1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( row_cast_fu_185_p1 );

    SC_METHOD(thread_icmp_fu_225_p2);
    sensitive << ( exitcond1_fu_204_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_5_fu_215_p4 );

    SC_METHOD(thread_img_0_data_stream_0_V_read);
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_img_0_data_stream_1_V_read);
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_img_0_data_stream_2_V_read);
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_img_1_data_stream_0_V_din);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( p_val_0_reg_642 );
    sensitive << ( sel_tmp2_fu_448_p2 );
    sensitive << ( p_val_0_2_fu_443_p3 );

    SC_METHOD(thread_img_1_data_stream_0_V_write);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_img_1_data_stream_1_V_din);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( p_val_1_reg_648 );
    sensitive << ( sel_tmp2_fu_448_p2 );
    sensitive << ( p_val_1_2_fu_460_p3 );

    SC_METHOD(thread_img_1_data_stream_1_V_write);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_img_1_data_stream_2_V_din);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( sel_tmp2_fu_448_p2 );
    sensitive << ( buffer_val_2_1_1_p_val_2_fu_438_p3 );
    sensitive << ( sel_tmp9_fu_473_p3 );

    SC_METHOD(thread_img_1_data_stream_2_V_write);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_p_val_0_2_fu_443_p3);
    sensitive << ( ap_reg_ppstg_icmp_reg_551_pp0_it2 );
    sensitive << ( ap_reg_ppstg_scl_val_0_reg_579_pp0_it2 );
    sensitive << ( p_val_0_reg_642 );

    SC_METHOD(thread_p_val_0_fu_337_p3);
    sensitive << ( buffer_val_0_1_load_reg_559 );
    sensitive << ( brmerge_fu_315_p2 );
    sensitive << ( buffer_val_0_1_1_scl_val_0_fu_331_p3 );

    SC_METHOD(thread_p_val_1_2_fu_460_p3);
    sensitive << ( ap_reg_ppstg_icmp_reg_551_pp0_it2 );
    sensitive << ( ap_reg_ppstg_scl_val_1_reg_585_pp0_it2 );
    sensitive << ( p_val_1_reg_648 );

    SC_METHOD(thread_p_val_1_fu_376_p3);
    sensitive << ( buffer_val_1_1_load_reg_569 );
    sensitive << ( brmerge_1_fu_354_p2 );
    sensitive << ( buffer_val_1_1_1_scl_val_1_fu_370_p3 );

    SC_METHOD(thread_rev1_fu_321_p2);
    sensitive << ( ult1_reg_611 );

    SC_METHOD(thread_rev2_fu_344_p2);
    sensitive << ( ult2_reg_622 );

    SC_METHOD(thread_rev3_fu_360_p2);
    sensitive << ( ult3_reg_627 );

    SC_METHOD(thread_rev4_fu_394_p2);
    sensitive << ( ult4_fu_388_p2 );

    SC_METHOD(thread_rev5_fu_417_p2);
    sensitive << ( ult5_fu_412_p2 );

    SC_METHOD(thread_rev_fu_305_p2);
    sensitive << ( ult_reg_606 );

    SC_METHOD(thread_row_1_fu_194_p2);
    sensitive << ( row_reg_155 );

    SC_METHOD(thread_row_cast_fu_185_p1);
    sensitive << ( row_reg_155 );

    SC_METHOD(thread_sel_tmp2_fu_448_p2);
    sensitive << ( ap_reg_ppstg_icmp_reg_551_pp0_it2 );
    sensitive << ( brmerge_2_reg_654 );

    SC_METHOD(thread_sel_tmp9_fu_473_p3);
    sensitive << ( ap_reg_ppstg_icmp_reg_551_pp0_it2 );
    sensitive << ( ap_reg_ppstg_p_val_2_reg_591_pp0_it2 );
    sensitive << ( buffer_val_2_1_load_reg_632 );

    SC_METHOD(thread_tmp_3_fu_177_p1);
    sensitive << ( rows );

    SC_METHOD(thread_tmp_4_fu_181_p1);
    sensitive << ( cols );

    SC_METHOD(thread_tmp_5_fu_215_p4);
    sensitive << ( col_reg_166 );

    SC_METHOD(thread_ult1_fu_255_p2);
    sensitive << ( img_0_data_stream_0_V_dout );
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buffer_val_0_1_1_fu_84 );

    SC_METHOD(thread_ult2_fu_267_p2);
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buffer_val_1_1_fu_88 );
    sensitive << ( buffer_val_1_1_1_fu_92 );

    SC_METHOD(thread_ult3_fu_273_p2);
    sensitive << ( img_0_data_stream_1_V_dout );
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buffer_val_1_1_1_fu_92 );

    SC_METHOD(thread_ult4_fu_388_p2);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it1 );
    sensitive << ( buffer_val_2_1_fu_96 );
    sensitive << ( buffer_val_2_1_1_fu_100 );

    SC_METHOD(thread_ult5_fu_412_p2);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond1_reg_542_pp0_it1 );
    sensitive << ( p_val_2_reg_591 );
    sensitive << ( buffer_val_2_1_1_fu_100 );

    SC_METHOD(thread_ult_fu_249_p2);
    sensitive << ( exitcond1_reg_542 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( buffer_val_0_1_fu_80 );
    sensitive << ( buffer_val_0_1_1_fu_84 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_63 );
    sensitive << ( exitcond2_fu_189_p2 );
    sensitive << ( exitcond1_fu_204_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_bdd_116 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_Loop_1_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, img_1_data_stream_0_V_din, "(port)img_1_data_stream_0_V_din");
    sc_trace(mVcdFile, img_1_data_stream_0_V_full_n, "(port)img_1_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_write, "(port)img_1_data_stream_0_V_write");
    sc_trace(mVcdFile, img_1_data_stream_1_V_din, "(port)img_1_data_stream_1_V_din");
    sc_trace(mVcdFile, img_1_data_stream_1_V_full_n, "(port)img_1_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_1_V_write, "(port)img_1_data_stream_1_V_write");
    sc_trace(mVcdFile, img_1_data_stream_2_V_din, "(port)img_1_data_stream_2_V_din");
    sc_trace(mVcdFile, img_1_data_stream_2_V_full_n, "(port)img_1_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_2_V_write, "(port)img_1_data_stream_2_V_write");
    sc_trace(mVcdFile, img_0_data_stream_0_V_dout, "(port)img_0_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_V_empty_n, "(port)img_0_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_read, "(port)img_0_data_stream_0_V_read");
    sc_trace(mVcdFile, img_0_data_stream_1_V_dout, "(port)img_0_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_V_empty_n, "(port)img_0_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_V_read, "(port)img_0_data_stream_1_V_read");
    sc_trace(mVcdFile, img_0_data_stream_2_V_dout, "(port)img_0_data_stream_2_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_V_empty_n, "(port)img_0_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_V_read, "(port)img_0_data_stream_2_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, col_reg_166, "col_reg_166");
    sc_trace(mVcdFile, tmp_3_fu_177_p1, "tmp_3_fu_177_p1");
    sc_trace(mVcdFile, ap_sig_bdd_63, "ap_sig_bdd_63");
    sc_trace(mVcdFile, tmp_4_fu_181_p1, "tmp_4_fu_181_p1");
    sc_trace(mVcdFile, exitcond2_fu_189_p2, "exitcond2_fu_189_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_75, "ap_sig_bdd_75");
    sc_trace(mVcdFile, row_1_fu_194_p2, "row_1_fu_194_p2");
    sc_trace(mVcdFile, row_1_reg_537, "row_1_reg_537");
    sc_trace(mVcdFile, exitcond1_fu_204_p2, "exitcond1_fu_204_p2");
    sc_trace(mVcdFile, exitcond1_reg_542, "exitcond1_reg_542");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_86, "ap_sig_bdd_86");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_100, "ap_sig_bdd_100");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_542_pp0_it2, "ap_reg_ppstg_exitcond1_reg_542_pp0_it2");
    sc_trace(mVcdFile, ap_sig_bdd_116, "ap_sig_bdd_116");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond1_reg_542_pp0_it1, "ap_reg_ppstg_exitcond1_reg_542_pp0_it1");
    sc_trace(mVcdFile, col_1_fu_209_p2, "col_1_fu_209_p2");
    sc_trace(mVcdFile, icmp_fu_225_p2, "icmp_fu_225_p2");
    sc_trace(mVcdFile, icmp_reg_551, "icmp_reg_551");
    sc_trace(mVcdFile, ap_reg_ppstg_icmp_reg_551_pp0_it1, "ap_reg_ppstg_icmp_reg_551_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_icmp_reg_551_pp0_it2, "ap_reg_ppstg_icmp_reg_551_pp0_it2");
    sc_trace(mVcdFile, buffer_val_0_1_load_reg_559, "buffer_val_0_1_load_reg_559");
    sc_trace(mVcdFile, buffer_val_0_1_1_load_reg_564, "buffer_val_0_1_1_load_reg_564");
    sc_trace(mVcdFile, buffer_val_1_1_load_reg_569, "buffer_val_1_1_load_reg_569");
    sc_trace(mVcdFile, buffer_val_1_1_1_load_reg_574, "buffer_val_1_1_1_load_reg_574");
    sc_trace(mVcdFile, scl_val_0_reg_579, "scl_val_0_reg_579");
    sc_trace(mVcdFile, ap_reg_ppstg_scl_val_0_reg_579_pp0_it2, "ap_reg_ppstg_scl_val_0_reg_579_pp0_it2");
    sc_trace(mVcdFile, scl_val_1_reg_585, "scl_val_1_reg_585");
    sc_trace(mVcdFile, ap_reg_ppstg_scl_val_1_reg_585_pp0_it2, "ap_reg_ppstg_scl_val_1_reg_585_pp0_it2");
    sc_trace(mVcdFile, p_val_2_reg_591, "p_val_2_reg_591");
    sc_trace(mVcdFile, ap_reg_ppstg_p_val_2_reg_591_pp0_it2, "ap_reg_ppstg_p_val_2_reg_591_pp0_it2");
    sc_trace(mVcdFile, c_fu_243_p2, "c_fu_243_p2");
    sc_trace(mVcdFile, c_reg_600, "c_reg_600");
    sc_trace(mVcdFile, ult_fu_249_p2, "ult_fu_249_p2");
    sc_trace(mVcdFile, ult_reg_606, "ult_reg_606");
    sc_trace(mVcdFile, ult1_fu_255_p2, "ult1_fu_255_p2");
    sc_trace(mVcdFile, ult1_reg_611, "ult1_reg_611");
    sc_trace(mVcdFile, c_1_fu_261_p2, "c_1_fu_261_p2");
    sc_trace(mVcdFile, c_1_reg_616, "c_1_reg_616");
    sc_trace(mVcdFile, ult2_fu_267_p2, "ult2_fu_267_p2");
    sc_trace(mVcdFile, ult2_reg_622, "ult2_reg_622");
    sc_trace(mVcdFile, ult3_fu_273_p2, "ult3_fu_273_p2");
    sc_trace(mVcdFile, ult3_reg_627, "ult3_reg_627");
    sc_trace(mVcdFile, buffer_val_2_1_load_reg_632, "buffer_val_2_1_load_reg_632");
    sc_trace(mVcdFile, buffer_val_2_1_1_load_reg_637, "buffer_val_2_1_1_load_reg_637");
    sc_trace(mVcdFile, p_val_0_fu_337_p3, "p_val_0_fu_337_p3");
    sc_trace(mVcdFile, p_val_0_reg_642, "p_val_0_reg_642");
    sc_trace(mVcdFile, p_val_1_fu_376_p3, "p_val_1_fu_376_p3");
    sc_trace(mVcdFile, p_val_1_reg_648, "p_val_1_reg_648");
    sc_trace(mVcdFile, brmerge_2_fu_406_p2, "brmerge_2_fu_406_p2");
    sc_trace(mVcdFile, brmerge_2_reg_654, "brmerge_2_reg_654");
    sc_trace(mVcdFile, brmerge1_2_fu_423_p2, "brmerge1_2_fu_423_p2");
    sc_trace(mVcdFile, brmerge1_2_reg_659, "brmerge1_2_reg_659");
    sc_trace(mVcdFile, row_reg_155, "row_reg_155");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_3, "ap_sig_cseq_ST_st7_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_195, "ap_sig_bdd_195");
    sc_trace(mVcdFile, buffer_val_0_1_fu_80, "buffer_val_0_1_fu_80");
    sc_trace(mVcdFile, buffer_val_0_1_1_fu_84, "buffer_val_0_1_1_fu_84");
    sc_trace(mVcdFile, buffer_val_1_1_fu_88, "buffer_val_1_1_fu_88");
    sc_trace(mVcdFile, buffer_val_1_1_1_fu_92, "buffer_val_1_1_1_fu_92");
    sc_trace(mVcdFile, buffer_val_2_1_fu_96, "buffer_val_2_1_fu_96");
    sc_trace(mVcdFile, buffer_val_2_1_1_fu_100, "buffer_val_2_1_1_fu_100");
    sc_trace(mVcdFile, row_cast_fu_185_p1, "row_cast_fu_185_p1");
    sc_trace(mVcdFile, col_cast_fu_200_p1, "col_cast_fu_200_p1");
    sc_trace(mVcdFile, tmp_5_fu_215_p4, "tmp_5_fu_215_p4");
    sc_trace(mVcdFile, rev_fu_305_p2, "rev_fu_305_p2");
    sc_trace(mVcdFile, c_0_not_fu_310_p2, "c_0_not_fu_310_p2");
    sc_trace(mVcdFile, rev1_fu_321_p2, "rev1_fu_321_p2");
    sc_trace(mVcdFile, brmerge1_fu_326_p2, "brmerge1_fu_326_p2");
    sc_trace(mVcdFile, brmerge_fu_315_p2, "brmerge_fu_315_p2");
    sc_trace(mVcdFile, buffer_val_0_1_1_scl_val_0_fu_331_p3, "buffer_val_0_1_1_scl_val_0_fu_331_p3");
    sc_trace(mVcdFile, rev2_fu_344_p2, "rev2_fu_344_p2");
    sc_trace(mVcdFile, c_0_not_1_fu_349_p2, "c_0_not_1_fu_349_p2");
    sc_trace(mVcdFile, rev3_fu_360_p2, "rev3_fu_360_p2");
    sc_trace(mVcdFile, brmerge1_1_fu_365_p2, "brmerge1_1_fu_365_p2");
    sc_trace(mVcdFile, brmerge_1_fu_354_p2, "brmerge_1_fu_354_p2");
    sc_trace(mVcdFile, buffer_val_1_1_1_scl_val_1_fu_370_p3, "buffer_val_1_1_1_scl_val_1_fu_370_p3");
    sc_trace(mVcdFile, ult4_fu_388_p2, "ult4_fu_388_p2");
    sc_trace(mVcdFile, c_2_fu_383_p2, "c_2_fu_383_p2");
    sc_trace(mVcdFile, rev4_fu_394_p2, "rev4_fu_394_p2");
    sc_trace(mVcdFile, c_0_not_2_fu_400_p2, "c_0_not_2_fu_400_p2");
    sc_trace(mVcdFile, ult5_fu_412_p2, "ult5_fu_412_p2");
    sc_trace(mVcdFile, rev5_fu_417_p2, "rev5_fu_417_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_448_p2, "sel_tmp2_fu_448_p2");
    sc_trace(mVcdFile, p_val_0_2_fu_443_p3, "p_val_0_2_fu_443_p3");
    sc_trace(mVcdFile, p_val_1_2_fu_460_p3, "p_val_1_2_fu_460_p3");
    sc_trace(mVcdFile, buffer_val_2_1_1_p_val_2_fu_438_p3, "buffer_val_2_1_1_p_val_2_fu_438_p3");
    sc_trace(mVcdFile, sel_tmp9_fu_473_p3, "sel_tmp9_fu_473_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_Loop_1_proc::~image_filter_Loop_1_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void image_filter_Loop_1_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && 
             !esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && 
             esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && 
                     !esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && 
         esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0))) {
        col_reg_166 = col_1_fu_209_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0))) {
        col_reg_166 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_63.read())) {
        row_reg_155 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_3.read())) {
        row_reg_155 = row_1_reg_537.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        ap_reg_ppstg_exitcond1_reg_542_pp0_it1 = exitcond1_reg_542.read();
        ap_reg_ppstg_icmp_reg_551_pp0_it1 = icmp_reg_551.read();
        exitcond1_reg_542 = exitcond1_fu_204_p2.read();
    }
    if (!((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())))) {
        ap_reg_ppstg_exitcond1_reg_542_pp0_it2 = ap_reg_ppstg_exitcond1_reg_542_pp0_it1.read();
        ap_reg_ppstg_icmp_reg_551_pp0_it2 = ap_reg_ppstg_icmp_reg_551_pp0_it1.read();
        ap_reg_ppstg_p_val_2_reg_591_pp0_it2 = p_val_2_reg_591.read();
        ap_reg_ppstg_scl_val_0_reg_579_pp0_it2 = scl_val_0_reg_579.read();
        ap_reg_ppstg_scl_val_1_reg_585_pp0_it2 = scl_val_1_reg_585.read();
    }
    if ((!((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it1.read()))) {
        brmerge1_2_reg_659 = brmerge1_2_fu_423_p2.read();
        brmerge_2_reg_654 = brmerge_2_fu_406_p2.read();
        buffer_val_2_1_1_load_reg_637 = buffer_val_2_1_1_fu_100.read();
        buffer_val_2_1_load_reg_632 = buffer_val_2_1_fu_96.read();
        p_val_0_reg_642 = p_val_0_fu_337_p3.read();
        p_val_1_reg_648 = p_val_1_fu_376_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        buffer_val_0_1_1_fu_84 = buffer_val_0_1_fu_80.read();
        buffer_val_0_1_fu_80 = img_0_data_stream_0_V_dout.read();
        buffer_val_1_1_1_fu_92 = buffer_val_1_1_fu_88.read();
        buffer_val_1_1_fu_88 = img_0_data_stream_1_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        buffer_val_0_1_1_load_reg_564 = buffer_val_0_1_1_fu_84.read();
        buffer_val_0_1_load_reg_559 = buffer_val_0_1_fu_80.read();
        buffer_val_1_1_1_load_reg_574 = buffer_val_1_1_1_fu_92.read();
        buffer_val_1_1_load_reg_569 = buffer_val_1_1_fu_88.read();
        c_1_reg_616 = c_1_fu_261_p2.read();
        c_reg_600 = c_fu_243_p2.read();
        p_val_2_reg_591 = img_0_data_stream_2_V_dout.read();
        scl_val_0_reg_579 = img_0_data_stream_0_V_dout.read();
        scl_val_1_reg_585 = img_0_data_stream_1_V_dout.read();
        ult1_reg_611 = ult1_fu_255_p2.read();
        ult2_reg_622 = ult2_fu_267_p2.read();
        ult3_reg_627 = ult3_fu_273_p2.read();
        ult_reg_606 = ult_fu_249_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it1.read()))) {
        buffer_val_2_1_1_fu_100 = buffer_val_2_1_fu_96.read();
        buffer_val_2_1_fu_96 = p_val_2_reg_591.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0))) {
        icmp_reg_551 = icmp_fu_225_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        row_1_reg_537 = row_1_fu_194_p2.read();
    }
}

void image_filter_Loop_1_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_100() {
    ap_sig_bdd_100 = ((esl_seteq<1,1,1>(img_0_data_stream_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_0_data_stream_1_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_0_data_stream_2_V_empty_n.read(), ap_const_logic_0)));
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_116() {
    ap_sig_bdd_116 = ((esl_seteq<1,1,1>(img_1_data_stream_0_V_full_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it2.read()) && 
  esl_seteq<1,1,1>(img_1_data_stream_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it2.read()) && 
  esl_seteq<1,1,1>(img_1_data_stream_2_V_full_n.read(), ap_const_logic_0)));
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_195() {
    ap_sig_bdd_195 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_63() {
    ap_sig_bdd_63 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_75() {
    ap_sig_bdd_75 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_Loop_1_proc::thread_ap_sig_bdd_86() {
    ap_sig_bdd_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void image_filter_Loop_1_proc::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_86.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_75.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_ap_sig_cseq_ST_st7_fsm_3() {
    if (ap_sig_bdd_195.read()) {
        ap_sig_cseq_ST_st7_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_3 = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_brmerge1_1_fu_365_p2() {
    brmerge1_1_fu_365_p2 = (rev3_fu_360_p2.read() | c_1_reg_616.read());
}

void image_filter_Loop_1_proc::thread_brmerge1_2_fu_423_p2() {
    brmerge1_2_fu_423_p2 = (rev5_fu_417_p2.read() | c_2_fu_383_p2.read());
}

void image_filter_Loop_1_proc::thread_brmerge1_fu_326_p2() {
    brmerge1_fu_326_p2 = (rev1_fu_321_p2.read() | c_reg_600.read());
}

void image_filter_Loop_1_proc::thread_brmerge_1_fu_354_p2() {
    brmerge_1_fu_354_p2 = (rev2_fu_344_p2.read() | c_0_not_1_fu_349_p2.read());
}

void image_filter_Loop_1_proc::thread_brmerge_2_fu_406_p2() {
    brmerge_2_fu_406_p2 = (rev4_fu_394_p2.read() | c_0_not_2_fu_400_p2.read());
}

void image_filter_Loop_1_proc::thread_brmerge_fu_315_p2() {
    brmerge_fu_315_p2 = (rev_fu_305_p2.read() | c_0_not_fu_310_p2.read());
}

void image_filter_Loop_1_proc::thread_buffer_val_0_1_1_scl_val_0_fu_331_p3() {
    buffer_val_0_1_1_scl_val_0_fu_331_p3 = (!brmerge1_fu_326_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge1_fu_326_p2.read()[0].to_bool())? buffer_val_0_1_1_load_reg_564.read(): scl_val_0_reg_579.read());
}

void image_filter_Loop_1_proc::thread_buffer_val_1_1_1_scl_val_1_fu_370_p3() {
    buffer_val_1_1_1_scl_val_1_fu_370_p3 = (!brmerge1_1_fu_365_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge1_1_fu_365_p2.read()[0].to_bool())? buffer_val_1_1_1_load_reg_574.read(): scl_val_1_reg_585.read());
}

void image_filter_Loop_1_proc::thread_buffer_val_2_1_1_p_val_2_fu_438_p3() {
    buffer_val_2_1_1_p_val_2_fu_438_p3 = (!brmerge1_2_reg_659.read()[0].is_01())? sc_lv<8>(): ((brmerge1_2_reg_659.read()[0].to_bool())? buffer_val_2_1_1_load_reg_637.read(): ap_reg_ppstg_p_val_2_reg_591_pp0_it2.read());
}

void image_filter_Loop_1_proc::thread_c_0_not_1_fu_349_p2() {
    c_0_not_1_fu_349_p2 = (c_1_reg_616.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_c_0_not_2_fu_400_p2() {
    c_0_not_2_fu_400_p2 = (c_2_fu_383_p2.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_c_0_not_fu_310_p2() {
    c_0_not_fu_310_p2 = (c_reg_600.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_c_1_fu_261_p2() {
    c_1_fu_261_p2 = (!buffer_val_1_1_fu_88.read().is_01() || !img_0_data_stream_1_V_dout.read().is_01())? sc_lv<1>(): (sc_biguint<8>(buffer_val_1_1_fu_88.read()) > sc_biguint<8>(img_0_data_stream_1_V_dout.read()));
}

void image_filter_Loop_1_proc::thread_c_2_fu_383_p2() {
    c_2_fu_383_p2 = (!buffer_val_2_1_fu_96.read().is_01() || !p_val_2_reg_591.read().is_01())? sc_lv<1>(): (sc_biguint<8>(buffer_val_2_1_fu_96.read()) > sc_biguint<8>(p_val_2_reg_591.read()));
}

void image_filter_Loop_1_proc::thread_c_fu_243_p2() {
    c_fu_243_p2 = (!buffer_val_0_1_fu_80.read().is_01() || !img_0_data_stream_0_V_dout.read().is_01())? sc_lv<1>(): (sc_biguint<8>(buffer_val_0_1_fu_80.read()) > sc_biguint<8>(img_0_data_stream_0_V_dout.read()));
}

void image_filter_Loop_1_proc::thread_col_1_fu_209_p2() {
    col_1_fu_209_p2 = (!col_reg_166.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(col_reg_166.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_Loop_1_proc::thread_col_cast_fu_200_p1() {
    col_cast_fu_200_p1 = esl_zext<12,11>(col_reg_166.read());
}

void image_filter_Loop_1_proc::thread_exitcond1_fu_204_p2() {
    exitcond1_fu_204_p2 = (!col_cast_fu_200_p1.read().is_01() || !tmp_4_fu_181_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(col_cast_fu_200_p1.read() == tmp_4_fu_181_p1.read());
}

void image_filter_Loop_1_proc::thread_exitcond2_fu_189_p2() {
    exitcond2_fu_189_p2 = (!row_cast_fu_185_p1.read().is_01() || !tmp_3_fu_177_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(row_cast_fu_185_p1.read() == tmp_3_fu_177_p1.read());
}

void image_filter_Loop_1_proc::thread_icmp_fu_225_p2() {
    icmp_fu_225_p2 = (!tmp_5_fu_215_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_215_p4.read() != ap_const_lv10_0);
}

void image_filter_Loop_1_proc::thread_img_0_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        img_0_data_stream_0_V_read = ap_const_logic_1;
    } else {
        img_0_data_stream_0_V_read = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_img_0_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        img_0_data_stream_1_V_read = ap_const_logic_1;
    } else {
        img_0_data_stream_1_V_read = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_img_0_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond1_reg_542.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        img_0_data_stream_2_V_read = ap_const_logic_1;
    } else {
        img_0_data_stream_2_V_read = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_img_1_data_stream_0_V_din() {
    img_1_data_stream_0_V_din = (!sel_tmp2_fu_448_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp2_fu_448_p2.read()[0].to_bool())? p_val_0_reg_642.read(): p_val_0_2_fu_443_p3.read());
}

void image_filter_Loop_1_proc::thread_img_1_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        img_1_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_1_data_stream_0_V_write = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_img_1_data_stream_1_V_din() {
    img_1_data_stream_1_V_din = (!sel_tmp2_fu_448_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp2_fu_448_p2.read()[0].to_bool())? p_val_1_reg_648.read(): p_val_1_2_fu_460_p3.read());
}

void image_filter_Loop_1_proc::thread_img_1_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        img_1_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_1_data_stream_1_V_write = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_img_1_data_stream_2_V_din() {
    img_1_data_stream_2_V_din = (!sel_tmp2_fu_448_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp2_fu_448_p2.read()[0].to_bool())? buffer_val_2_1_1_p_val_2_fu_438_p3.read(): sel_tmp9_fu_473_p3.read());
}

void image_filter_Loop_1_proc::thread_img_1_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond1_reg_542_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))))) {
        img_1_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_1_data_stream_2_V_write = ap_const_logic_0;
    }
}

void image_filter_Loop_1_proc::thread_p_val_0_2_fu_443_p3() {
    p_val_0_2_fu_443_p3 = (!ap_reg_ppstg_icmp_reg_551_pp0_it2.read()[0].is_01())? sc_lv<8>(): ((ap_reg_ppstg_icmp_reg_551_pp0_it2.read()[0].to_bool())? p_val_0_reg_642.read(): ap_reg_ppstg_scl_val_0_reg_579_pp0_it2.read());
}

void image_filter_Loop_1_proc::thread_p_val_0_fu_337_p3() {
    p_val_0_fu_337_p3 = (!brmerge_fu_315_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_fu_315_p2.read()[0].to_bool())? buffer_val_0_1_1_scl_val_0_fu_331_p3.read(): buffer_val_0_1_load_reg_559.read());
}

void image_filter_Loop_1_proc::thread_p_val_1_2_fu_460_p3() {
    p_val_1_2_fu_460_p3 = (!ap_reg_ppstg_icmp_reg_551_pp0_it2.read()[0].is_01())? sc_lv<8>(): ((ap_reg_ppstg_icmp_reg_551_pp0_it2.read()[0].to_bool())? p_val_1_reg_648.read(): ap_reg_ppstg_scl_val_1_reg_585_pp0_it2.read());
}

void image_filter_Loop_1_proc::thread_p_val_1_fu_376_p3() {
    p_val_1_fu_376_p3 = (!brmerge_1_fu_354_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_1_fu_354_p2.read()[0].to_bool())? buffer_val_1_1_1_scl_val_1_fu_370_p3.read(): buffer_val_1_1_load_reg_569.read());
}

void image_filter_Loop_1_proc::thread_rev1_fu_321_p2() {
    rev1_fu_321_p2 = (ult1_reg_611.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_rev2_fu_344_p2() {
    rev2_fu_344_p2 = (ult2_reg_622.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_rev3_fu_360_p2() {
    rev3_fu_360_p2 = (ult3_reg_627.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_rev4_fu_394_p2() {
    rev4_fu_394_p2 = (ult4_fu_388_p2.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_rev5_fu_417_p2() {
    rev5_fu_417_p2 = (ult5_fu_412_p2.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_rev_fu_305_p2() {
    rev_fu_305_p2 = (ult_reg_606.read() ^ ap_const_lv1_1);
}

void image_filter_Loop_1_proc::thread_row_1_fu_194_p2() {
    row_1_fu_194_p2 = (!row_reg_155.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(row_reg_155.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_Loop_1_proc::thread_row_cast_fu_185_p1() {
    row_cast_fu_185_p1 = esl_zext<12,11>(row_reg_155.read());
}

void image_filter_Loop_1_proc::thread_sel_tmp2_fu_448_p2() {
    sel_tmp2_fu_448_p2 = (ap_reg_ppstg_icmp_reg_551_pp0_it2.read() & brmerge_2_reg_654.read());
}

void image_filter_Loop_1_proc::thread_sel_tmp9_fu_473_p3() {
    sel_tmp9_fu_473_p3 = (!ap_reg_ppstg_icmp_reg_551_pp0_it2.read()[0].is_01())? sc_lv<8>(): ((ap_reg_ppstg_icmp_reg_551_pp0_it2.read()[0].to_bool())? buffer_val_2_1_load_reg_632.read(): ap_reg_ppstg_p_val_2_reg_591_pp0_it2.read());
}

void image_filter_Loop_1_proc::thread_tmp_3_fu_177_p1() {
    tmp_3_fu_177_p1 = rows.read().range(12-1, 0);
}

void image_filter_Loop_1_proc::thread_tmp_4_fu_181_p1() {
    tmp_4_fu_181_p1 = cols.read().range(12-1, 0);
}

void image_filter_Loop_1_proc::thread_tmp_5_fu_215_p4() {
    tmp_5_fu_215_p4 = col_reg_166.read().range(10, 1);
}

void image_filter_Loop_1_proc::thread_ult1_fu_255_p2() {
    ult1_fu_255_p2 = (!img_0_data_stream_0_V_dout.read().is_01() || !buffer_val_0_1_1_fu_84.read().is_01())? sc_lv<1>(): (sc_biguint<8>(img_0_data_stream_0_V_dout.read()) < sc_biguint<8>(buffer_val_0_1_1_fu_84.read()));
}

void image_filter_Loop_1_proc::thread_ult2_fu_267_p2() {
    ult2_fu_267_p2 = (!buffer_val_1_1_fu_88.read().is_01() || !buffer_val_1_1_1_fu_92.read().is_01())? sc_lv<1>(): (sc_biguint<8>(buffer_val_1_1_fu_88.read()) < sc_biguint<8>(buffer_val_1_1_1_fu_92.read()));
}

void image_filter_Loop_1_proc::thread_ult3_fu_273_p2() {
    ult3_fu_273_p2 = (!img_0_data_stream_1_V_dout.read().is_01() || !buffer_val_1_1_1_fu_92.read().is_01())? sc_lv<1>(): (sc_biguint<8>(img_0_data_stream_1_V_dout.read()) < sc_biguint<8>(buffer_val_1_1_1_fu_92.read()));
}

void image_filter_Loop_1_proc::thread_ult4_fu_388_p2() {
    ult4_fu_388_p2 = (!buffer_val_2_1_fu_96.read().is_01() || !buffer_val_2_1_1_fu_100.read().is_01())? sc_lv<1>(): (sc_biguint<8>(buffer_val_2_1_fu_96.read()) < sc_biguint<8>(buffer_val_2_1_1_fu_100.read()));
}

void image_filter_Loop_1_proc::thread_ult5_fu_412_p2() {
    ult5_fu_412_p2 = (!p_val_2_reg_591.read().is_01() || !buffer_val_2_1_1_fu_100.read().is_01())? sc_lv<1>(): (sc_biguint<8>(p_val_2_reg_591.read()) < sc_biguint<8>(buffer_val_2_1_1_fu_100.read()));
}

void image_filter_Loop_1_proc::thread_ult_fu_249_p2() {
    ult_fu_249_p2 = (!buffer_val_0_1_fu_80.read().is_01() || !buffer_val_0_1_1_fu_84.read().is_01())? sc_lv<1>(): (sc_biguint<8>(buffer_val_0_1_fu_80.read()) < sc_biguint<8>(buffer_val_0_1_1_fu_84.read()));
}

void image_filter_Loop_1_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_63.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond2_fu_189_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && !esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
  !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_116.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()))) && 
  !esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st7_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

