// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter_SubS.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_SubS::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_SubS::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> image_filter_SubS::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> image_filter_SubS::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> image_filter_SubS::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> image_filter_SubS::ap_ST_st6_fsm_3 = "1000";
const sc_lv<32> image_filter_SubS::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_SubS::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_SubS::ap_const_lv32_1 = "1";
const sc_lv<32> image_filter_SubS::ap_const_lv32_2 = "10";
const sc_lv<1> image_filter_SubS::ap_const_lv1_0 = "0";
const sc_lv<11> image_filter_SubS::ap_const_lv11_0 = "00000000000";
const sc_lv<32> image_filter_SubS::ap_const_lv32_3 = "11";
const sc_lv<11> image_filter_SubS::ap_const_lv11_1 = "1";
const sc_lv<9> image_filter_SubS::ap_const_lv9_1CE = "111001110";
const sc_lv<32> image_filter_SubS::ap_const_lv32_8 = "1000";
const sc_lv<8> image_filter_SubS::ap_const_lv8_0 = "00000000";

image_filter_SubS::image_filter_SubS(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond7_i_fu_149_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond7_i_fu_149_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_100);
    sensitive << ( src_data_stream_0_V_empty_n );
    sensitive << ( src_data_stream_1_V_empty_n );
    sensitive << ( src_data_stream_2_V_empty_n );
    sensitive << ( exitcond8_i_reg_281 );

    SC_METHOD(thread_ap_sig_bdd_114);
    sensitive << ( dst_data_stream_0_V_full_n );
    sensitive << ( dst_data_stream_1_V_full_n );
    sensitive << ( dst_data_stream_2_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );

    SC_METHOD(thread_ap_sig_bdd_154);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_63);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_75);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_75 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_3);
    sensitive << ( ap_sig_bdd_154 );

    SC_METHOD(thread_dst_data_stream_0_V_din);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_reg_290 );
    sensitive << ( p_Val2_21_reg_295 );

    SC_METHOD(thread_dst_data_stream_0_V_write);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_dst_data_stream_1_V_din);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_82_reg_300 );
    sensitive << ( p_Val2_24_reg_305 );

    SC_METHOD(thread_dst_data_stream_1_V_write);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_dst_data_stream_2_V_din);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_84_reg_310 );
    sensitive << ( p_Val2_26_reg_315 );

    SC_METHOD(thread_dst_data_stream_2_V_write);
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_exitcond7_i_fu_149_p2);
    sensitive << ( src_rows_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_i_cast_fu_145_p1 );

    SC_METHOD(thread_exitcond8_i_fu_164_p2);
    sensitive << ( src_cols_V_read );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( p_7_i_cast_fu_160_p1 );

    SC_METHOD(thread_i_V_fu_154_p2);
    sensitive << ( p_i_reg_123 );

    SC_METHOD(thread_j_V_fu_169_p2);
    sensitive << ( p_7_i_reg_134 );

    SC_METHOD(thread_lhs_V_1_i_fu_197_p1);
    sensitive << ( src_data_stream_1_V_dout );

    SC_METHOD(thread_lhs_V_2_i_fu_219_p1);
    sensitive << ( src_data_stream_2_V_dout );

    SC_METHOD(thread_lhs_V_i_fu_175_p1);
    sensitive << ( src_data_stream_0_V_dout );

    SC_METHOD(thread_p_7_i_cast_fu_160_p1);
    sensitive << ( p_7_i_reg_134 );

    SC_METHOD(thread_p_Val2_20_fu_179_p2);
    sensitive << ( lhs_V_i_fu_175_p1 );

    SC_METHOD(thread_p_Val2_21_fu_193_p1);
    sensitive << ( p_Val2_20_fu_179_p2 );

    SC_METHOD(thread_p_Val2_23_fu_201_p2);
    sensitive << ( lhs_V_1_i_fu_197_p1 );

    SC_METHOD(thread_p_Val2_24_fu_215_p1);
    sensitive << ( p_Val2_23_fu_201_p2 );

    SC_METHOD(thread_p_Val2_26_fu_237_p1);
    sensitive << ( p_Val2_s_fu_223_p2 );

    SC_METHOD(thread_p_Val2_s_fu_223_p2);
    sensitive << ( lhs_V_2_i_fu_219_p1 );

    SC_METHOD(thread_p_i_cast_fu_145_p1);
    sensitive << ( p_i_reg_123 );

    SC_METHOD(thread_src_data_stream_0_V_read);
    sensitive << ( exitcond8_i_reg_281 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_src_data_stream_1_V_read);
    sensitive << ( exitcond8_i_reg_281 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_src_data_stream_2_V_read);
    sensitive << ( exitcond8_i_reg_281 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_63 );
    sensitive << ( exitcond7_i_fu_149_p2 );
    sensitive << ( exitcond8_i_fu_164_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_100 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_114 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_SubS_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_rows_V_read, "(port)src_rows_V_read");
    sc_trace(mVcdFile, src_cols_V_read, "(port)src_cols_V_read");
    sc_trace(mVcdFile, src_data_stream_0_V_dout, "(port)src_data_stream_0_V_dout");
    sc_trace(mVcdFile, src_data_stream_0_V_empty_n, "(port)src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_0_V_read, "(port)src_data_stream_0_V_read");
    sc_trace(mVcdFile, src_data_stream_1_V_dout, "(port)src_data_stream_1_V_dout");
    sc_trace(mVcdFile, src_data_stream_1_V_empty_n, "(port)src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_1_V_read, "(port)src_data_stream_1_V_read");
    sc_trace(mVcdFile, src_data_stream_2_V_dout, "(port)src_data_stream_2_V_dout");
    sc_trace(mVcdFile, src_data_stream_2_V_empty_n, "(port)src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_2_V_read, "(port)src_data_stream_2_V_read");
    sc_trace(mVcdFile, dst_data_stream_0_V_din, "(port)dst_data_stream_0_V_din");
    sc_trace(mVcdFile, dst_data_stream_0_V_full_n, "(port)dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_0_V_write, "(port)dst_data_stream_0_V_write");
    sc_trace(mVcdFile, dst_data_stream_1_V_din, "(port)dst_data_stream_1_V_din");
    sc_trace(mVcdFile, dst_data_stream_1_V_full_n, "(port)dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_1_V_write, "(port)dst_data_stream_1_V_write");
    sc_trace(mVcdFile, dst_data_stream_2_V_din, "(port)dst_data_stream_2_V_din");
    sc_trace(mVcdFile, dst_data_stream_2_V_full_n, "(port)dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_2_V_write, "(port)dst_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, p_7_i_reg_134, "p_7_i_reg_134");
    sc_trace(mVcdFile, ap_sig_bdd_63, "ap_sig_bdd_63");
    sc_trace(mVcdFile, exitcond7_i_fu_149_p2, "exitcond7_i_fu_149_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_75, "ap_sig_bdd_75");
    sc_trace(mVcdFile, i_V_fu_154_p2, "i_V_fu_154_p2");
    sc_trace(mVcdFile, i_V_reg_276, "i_V_reg_276");
    sc_trace(mVcdFile, exitcond8_i_fu_164_p2, "exitcond8_i_fu_164_p2");
    sc_trace(mVcdFile, exitcond8_i_reg_281, "exitcond8_i_reg_281");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_86, "ap_sig_bdd_86");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_100, "ap_sig_bdd_100");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1, "ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1");
    sc_trace(mVcdFile, ap_sig_bdd_114, "ap_sig_bdd_114");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, j_V_fu_169_p2, "j_V_fu_169_p2");
    sc_trace(mVcdFile, tmp_reg_290, "tmp_reg_290");
    sc_trace(mVcdFile, p_Val2_21_fu_193_p1, "p_Val2_21_fu_193_p1");
    sc_trace(mVcdFile, p_Val2_21_reg_295, "p_Val2_21_reg_295");
    sc_trace(mVcdFile, tmp_82_reg_300, "tmp_82_reg_300");
    sc_trace(mVcdFile, p_Val2_24_fu_215_p1, "p_Val2_24_fu_215_p1");
    sc_trace(mVcdFile, p_Val2_24_reg_305, "p_Val2_24_reg_305");
    sc_trace(mVcdFile, tmp_84_reg_310, "tmp_84_reg_310");
    sc_trace(mVcdFile, p_Val2_26_fu_237_p1, "p_Val2_26_fu_237_p1");
    sc_trace(mVcdFile, p_Val2_26_reg_315, "p_Val2_26_reg_315");
    sc_trace(mVcdFile, p_i_reg_123, "p_i_reg_123");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_3, "ap_sig_cseq_ST_st6_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_154, "ap_sig_bdd_154");
    sc_trace(mVcdFile, p_i_cast_fu_145_p1, "p_i_cast_fu_145_p1");
    sc_trace(mVcdFile, p_7_i_cast_fu_160_p1, "p_7_i_cast_fu_160_p1");
    sc_trace(mVcdFile, lhs_V_i_fu_175_p1, "lhs_V_i_fu_175_p1");
    sc_trace(mVcdFile, p_Val2_20_fu_179_p2, "p_Val2_20_fu_179_p2");
    sc_trace(mVcdFile, lhs_V_1_i_fu_197_p1, "lhs_V_1_i_fu_197_p1");
    sc_trace(mVcdFile, p_Val2_23_fu_201_p2, "p_Val2_23_fu_201_p2");
    sc_trace(mVcdFile, lhs_V_2_i_fu_219_p1, "lhs_V_2_i_fu_219_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_223_p2, "p_Val2_s_fu_223_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_SubS::~image_filter_SubS() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void image_filter_SubS::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
             !esl_seteq<1,1,1>(exitcond8_i_fu_164_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
             esl_seteq<1,1,1>(exitcond8_i_fu_164_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
                     !esl_seteq<1,1,1>(exitcond8_i_fu_164_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
         esl_seteq<1,1,1>(exitcond8_i_fu_164_p2.read(), ap_const_lv1_0))) {
        p_7_i_reg_134 = j_V_fu_169_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0))) {
        p_7_i_reg_134 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read())) {
        p_i_reg_123 = i_V_reg_276.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_63.read())) {
        p_i_reg_123 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1 = exitcond8_i_reg_281.read();
        exitcond8_i_reg_281 = exitcond8_i_fu_164_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_276 = i_V_fu_154_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        p_Val2_21_reg_295 = p_Val2_21_fu_193_p1.read();
        p_Val2_24_reg_305 = p_Val2_24_fu_215_p1.read();
        p_Val2_26_reg_315 = p_Val2_26_fu_237_p1.read();
        tmp_82_reg_300 = p_Val2_23_fu_201_p2.read().range(8, 8);
        tmp_84_reg_310 = p_Val2_s_fu_223_p2.read().range(8, 8);
        tmp_reg_290 = p_Val2_20_fu_179_p2.read().range(8, 8);
    }
}

void image_filter_SubS::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_sig_bdd_100() {
    ap_sig_bdd_100 = ((esl_seteq<1,1,1>(src_data_stream_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(src_data_stream_1_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(src_data_stream_2_V_empty_n.read(), ap_const_logic_0)));
}

void image_filter_SubS::thread_ap_sig_bdd_114() {
    ap_sig_bdd_114 = ((esl_seteq<1,1,1>(dst_data_stream_0_V_full_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1.read()) && 
  esl_seteq<1,1,1>(dst_data_stream_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1.read()) && 
  esl_seteq<1,1,1>(dst_data_stream_2_V_full_n.read(), ap_const_logic_0)));
}

void image_filter_SubS::thread_ap_sig_bdd_154() {
    ap_sig_bdd_154 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void image_filter_SubS::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_SubS::thread_ap_sig_bdd_63() {
    ap_sig_bdd_63 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_SubS::thread_ap_sig_bdd_75() {
    ap_sig_bdd_75 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_SubS::thread_ap_sig_bdd_86() {
    ap_sig_bdd_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void image_filter_SubS::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_86.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_75.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_sig_cseq_ST_st6_fsm_3() {
    if (ap_sig_bdd_154.read()) {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_dst_data_stream_0_V_din() {
    dst_data_stream_0_V_din = (!tmp_reg_290.read()[0].is_01())? sc_lv<8>(): ((tmp_reg_290.read()[0].to_bool())? ap_const_lv8_0: p_Val2_21_reg_295.read());
}

void image_filter_SubS::thread_dst_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        dst_data_stream_0_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_0_V_write = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_dst_data_stream_1_V_din() {
    dst_data_stream_1_V_din = (!tmp_82_reg_300.read()[0].is_01())? sc_lv<8>(): ((tmp_82_reg_300.read()[0].to_bool())? ap_const_lv8_0: p_Val2_24_reg_305.read());
}

void image_filter_SubS::thread_dst_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        dst_data_stream_1_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_1_V_write = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_dst_data_stream_2_V_din() {
    dst_data_stream_2_V_din = (!tmp_84_reg_310.read()[0].is_01())? sc_lv<8>(): ((tmp_84_reg_310.read()[0].to_bool())? ap_const_lv8_0: p_Val2_26_reg_315.read());
}

void image_filter_SubS::thread_dst_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        dst_data_stream_2_V_write = ap_const_logic_1;
    } else {
        dst_data_stream_2_V_write = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_exitcond7_i_fu_149_p2() {
    exitcond7_i_fu_149_p2 = (!p_i_cast_fu_145_p1.read().is_01() || !src_rows_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(p_i_cast_fu_145_p1.read() == src_rows_V_read.read());
}

void image_filter_SubS::thread_exitcond8_i_fu_164_p2() {
    exitcond8_i_fu_164_p2 = (!p_7_i_cast_fu_160_p1.read().is_01() || !src_cols_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(p_7_i_cast_fu_160_p1.read() == src_cols_V_read.read());
}

void image_filter_SubS::thread_i_V_fu_154_p2() {
    i_V_fu_154_p2 = (!p_i_reg_123.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_i_reg_123.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_SubS::thread_j_V_fu_169_p2() {
    j_V_fu_169_p2 = (!p_7_i_reg_134.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_7_i_reg_134.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_SubS::thread_lhs_V_1_i_fu_197_p1() {
    lhs_V_1_i_fu_197_p1 = esl_zext<9,8>(src_data_stream_1_V_dout.read());
}

void image_filter_SubS::thread_lhs_V_2_i_fu_219_p1() {
    lhs_V_2_i_fu_219_p1 = esl_zext<9,8>(src_data_stream_2_V_dout.read());
}

void image_filter_SubS::thread_lhs_V_i_fu_175_p1() {
    lhs_V_i_fu_175_p1 = esl_zext<9,8>(src_data_stream_0_V_dout.read());
}

void image_filter_SubS::thread_p_7_i_cast_fu_160_p1() {
    p_7_i_cast_fu_160_p1 = esl_zext<12,11>(p_7_i_reg_134.read());
}

void image_filter_SubS::thread_p_Val2_20_fu_179_p2() {
    p_Val2_20_fu_179_p2 = (!ap_const_lv9_1CE.is_01() || !lhs_V_i_fu_175_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1CE) + sc_biguint<9>(lhs_V_i_fu_175_p1.read()));
}

void image_filter_SubS::thread_p_Val2_21_fu_193_p1() {
    p_Val2_21_fu_193_p1 = p_Val2_20_fu_179_p2.read().range(8-1, 0);
}

void image_filter_SubS::thread_p_Val2_23_fu_201_p2() {
    p_Val2_23_fu_201_p2 = (!ap_const_lv9_1CE.is_01() || !lhs_V_1_i_fu_197_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1CE) + sc_biguint<9>(lhs_V_1_i_fu_197_p1.read()));
}

void image_filter_SubS::thread_p_Val2_24_fu_215_p1() {
    p_Val2_24_fu_215_p1 = p_Val2_23_fu_201_p2.read().range(8-1, 0);
}

void image_filter_SubS::thread_p_Val2_26_fu_237_p1() {
    p_Val2_26_fu_237_p1 = p_Val2_s_fu_223_p2.read().range(8-1, 0);
}

void image_filter_SubS::thread_p_Val2_s_fu_223_p2() {
    p_Val2_s_fu_223_p2 = (!ap_const_lv9_1CE.is_01() || !lhs_V_2_i_fu_219_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1CE) + sc_biguint<9>(lhs_V_2_i_fu_219_p1.read()));
}

void image_filter_SubS::thread_p_i_cast_fu_145_p1() {
    p_i_cast_fu_145_p1 = esl_zext<12,11>(p_i_reg_123.read());
}

void image_filter_SubS::thread_src_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_src_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        src_data_stream_1_V_read = ap_const_logic_1;
    } else {
        src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_src_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond8_i_reg_281.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))))) {
        src_data_stream_2_V_read = ap_const_logic_1;
    } else {
        src_data_stream_2_V_read = ap_const_logic_0;
    }
}

void image_filter_SubS::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_63.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond7_i_fu_149_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && !esl_seteq<1,1,1>(exitcond8_i_fu_164_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((ap_sig_bdd_100.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (ap_sig_bdd_114.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) && 
  !esl_seteq<1,1,1>(exitcond8_i_fu_164_p2.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st6_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

