// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _image_filter_SubS_HH_
#define _image_filter_SubS_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct image_filter_SubS : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > src_rows_V_read;
    sc_in< sc_lv<12> > src_cols_V_read;
    sc_in< sc_lv<8> > src_data_stream_0_V_dout;
    sc_in< sc_logic > src_data_stream_0_V_empty_n;
    sc_out< sc_logic > src_data_stream_0_V_read;
    sc_in< sc_lv<8> > src_data_stream_1_V_dout;
    sc_in< sc_logic > src_data_stream_1_V_empty_n;
    sc_out< sc_logic > src_data_stream_1_V_read;
    sc_in< sc_lv<8> > src_data_stream_2_V_dout;
    sc_in< sc_logic > src_data_stream_2_V_empty_n;
    sc_out< sc_logic > src_data_stream_2_V_read;
    sc_out< sc_lv<8> > dst_data_stream_0_V_din;
    sc_in< sc_logic > dst_data_stream_0_V_full_n;
    sc_out< sc_logic > dst_data_stream_0_V_write;
    sc_out< sc_lv<8> > dst_data_stream_1_V_din;
    sc_in< sc_logic > dst_data_stream_1_V_full_n;
    sc_out< sc_logic > dst_data_stream_1_V_write;
    sc_out< sc_lv<8> > dst_data_stream_2_V_din;
    sc_in< sc_logic > dst_data_stream_2_V_full_n;
    sc_out< sc_logic > dst_data_stream_2_V_write;


    // Module declarations
    image_filter_SubS(sc_module_name name);
    SC_HAS_PROCESS(image_filter_SubS);

    ~image_filter_SubS();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_lv<11> > p_7_i_reg_134;
    sc_signal< bool > ap_sig_bdd_63;
    sc_signal< sc_lv<1> > exitcond7_i_fu_149_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_75;
    sc_signal< sc_lv<11> > i_V_fu_154_p2;
    sc_signal< sc_lv<11> > i_V_reg_276;
    sc_signal< sc_lv<1> > exitcond8_i_fu_164_p2;
    sc_signal< sc_lv<1> > exitcond8_i_reg_281;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_86;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_100;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond8_i_reg_281_pp0_it1;
    sc_signal< bool > ap_sig_bdd_114;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_lv<11> > j_V_fu_169_p2;
    sc_signal< sc_lv<1> > tmp_reg_290;
    sc_signal< sc_lv<8> > p_Val2_21_fu_193_p1;
    sc_signal< sc_lv<8> > p_Val2_21_reg_295;
    sc_signal< sc_lv<1> > tmp_82_reg_300;
    sc_signal< sc_lv<8> > p_Val2_24_fu_215_p1;
    sc_signal< sc_lv<8> > p_Val2_24_reg_305;
    sc_signal< sc_lv<1> > tmp_84_reg_310;
    sc_signal< sc_lv<8> > p_Val2_26_fu_237_p1;
    sc_signal< sc_lv<8> > p_Val2_26_reg_315;
    sc_signal< sc_lv<11> > p_i_reg_123;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_3;
    sc_signal< bool > ap_sig_bdd_154;
    sc_signal< sc_lv<12> > p_i_cast_fu_145_p1;
    sc_signal< sc_lv<12> > p_7_i_cast_fu_160_p1;
    sc_signal< sc_lv<9> > lhs_V_i_fu_175_p1;
    sc_signal< sc_lv<9> > p_Val2_20_fu_179_p2;
    sc_signal< sc_lv<9> > lhs_V_1_i_fu_197_p1;
    sc_signal< sc_lv<9> > p_Val2_23_fu_201_p2;
    sc_signal< sc_lv<9> > lhs_V_2_i_fu_219_p1;
    sc_signal< sc_lv<9> > p_Val2_s_fu_223_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_st1_fsm_0;
    static const sc_lv<4> ap_ST_st2_fsm_1;
    static const sc_lv<4> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<4> ap_ST_st6_fsm_3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<9> ap_const_lv9_1CE;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_100();
    void thread_ap_sig_bdd_114();
    void thread_ap_sig_bdd_154();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_63();
    void thread_ap_sig_bdd_75();
    void thread_ap_sig_bdd_86();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st6_fsm_3();
    void thread_dst_data_stream_0_V_din();
    void thread_dst_data_stream_0_V_write();
    void thread_dst_data_stream_1_V_din();
    void thread_dst_data_stream_1_V_write();
    void thread_dst_data_stream_2_V_din();
    void thread_dst_data_stream_2_V_write();
    void thread_exitcond7_i_fu_149_p2();
    void thread_exitcond8_i_fu_164_p2();
    void thread_i_V_fu_154_p2();
    void thread_j_V_fu_169_p2();
    void thread_lhs_V_1_i_fu_197_p1();
    void thread_lhs_V_2_i_fu_219_p1();
    void thread_lhs_V_i_fu_175_p1();
    void thread_p_7_i_cast_fu_160_p1();
    void thread_p_Val2_20_fu_179_p2();
    void thread_p_Val2_21_fu_193_p1();
    void thread_p_Val2_23_fu_201_p2();
    void thread_p_Val2_24_fu_215_p1();
    void thread_p_Val2_26_fu_237_p1();
    void thread_p_Val2_s_fu_223_p2();
    void thread_p_i_cast_fu_145_p1();
    void thread_src_data_stream_0_V_read();
    void thread_src_data_stream_1_V_read();
    void thread_src_data_stream_2_V_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
