// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> image_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<4> image_filter::ap_const_lv4_0 = "0000";
const sc_lv<1> image_filter::ap_const_lv1_0 = "0";
const sc_lv<32> image_filter::ap_const_lv32_B = "1011";
const sc_logic image_filter::ap_const_logic_1 = sc_dt::Log_1;
const bool image_filter::ap_true = true;

image_filter::image_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    image_filter_AXIvideo2Mat_U0 = new image_filter_AXIvideo2Mat("image_filter_AXIvideo2Mat_U0");
    image_filter_AXIvideo2Mat_U0->ap_clk(ap_clk);
    image_filter_AXIvideo2Mat_U0->ap_rst(ap_rst);
    image_filter_AXIvideo2Mat_U0->ap_start(image_filter_AXIvideo2Mat_U0_ap_start);
    image_filter_AXIvideo2Mat_U0->ap_done(image_filter_AXIvideo2Mat_U0_ap_done);
    image_filter_AXIvideo2Mat_U0->ap_continue(image_filter_AXIvideo2Mat_U0_ap_continue);
    image_filter_AXIvideo2Mat_U0->ap_idle(image_filter_AXIvideo2Mat_U0_ap_idle);
    image_filter_AXIvideo2Mat_U0->ap_ready(image_filter_AXIvideo2Mat_U0_ap_ready);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_data_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_data_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_data_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_keep_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_keep_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_keep_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_strb_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_strb_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_strb_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_user_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_user_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_user_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_last_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_last_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_last_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_id_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_id_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_id_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_dest_V_dout(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_dout);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_dest_V_empty_n(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_empty_n);
    image_filter_AXIvideo2Mat_U0->AXI_video_strm_V_dest_V_read(image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read);
    image_filter_AXIvideo2Mat_U0->rows(image_filter_AXIvideo2Mat_U0_rows);
    image_filter_AXIvideo2Mat_U0->cols(image_filter_AXIvideo2Mat_U0_cols);
    image_filter_AXIvideo2Mat_U0->img_data_stream_V_din(image_filter_AXIvideo2Mat_U0_img_data_stream_V_din);
    image_filter_AXIvideo2Mat_U0->img_data_stream_V_full_n(image_filter_AXIvideo2Mat_U0_img_data_stream_V_full_n);
    image_filter_AXIvideo2Mat_U0->img_data_stream_V_write(image_filter_AXIvideo2Mat_U0_img_data_stream_V_write);
    image_filter_Sobel_U0 = new image_filter_Sobel("image_filter_Sobel_U0");
    image_filter_Sobel_U0->ap_clk(ap_clk);
    image_filter_Sobel_U0->ap_rst(ap_rst);
    image_filter_Sobel_U0->ap_start(image_filter_Sobel_U0_ap_start);
    image_filter_Sobel_U0->ap_done(image_filter_Sobel_U0_ap_done);
    image_filter_Sobel_U0->ap_continue(image_filter_Sobel_U0_ap_continue);
    image_filter_Sobel_U0->ap_idle(image_filter_Sobel_U0_ap_idle);
    image_filter_Sobel_U0->ap_ready(image_filter_Sobel_U0_ap_ready);
    image_filter_Sobel_U0->rows(image_filter_Sobel_U0_rows);
    image_filter_Sobel_U0->cols(image_filter_Sobel_U0_cols);
    image_filter_Sobel_U0->p_src_data_stream_V_dout(image_filter_Sobel_U0_p_src_data_stream_V_dout);
    image_filter_Sobel_U0->p_src_data_stream_V_empty_n(image_filter_Sobel_U0_p_src_data_stream_V_empty_n);
    image_filter_Sobel_U0->p_src_data_stream_V_read(image_filter_Sobel_U0_p_src_data_stream_V_read);
    image_filter_Sobel_U0->p_dst_data_stream_V_din(image_filter_Sobel_U0_p_dst_data_stream_V_din);
    image_filter_Sobel_U0->p_dst_data_stream_V_full_n(image_filter_Sobel_U0_p_dst_data_stream_V_full_n);
    image_filter_Sobel_U0->p_dst_data_stream_V_write(image_filter_Sobel_U0_p_dst_data_stream_V_write);
    image_filter_Sobel_1_U0 = new image_filter_Sobel_1("image_filter_Sobel_1_U0");
    image_filter_Sobel_1_U0->ap_clk(ap_clk);
    image_filter_Sobel_1_U0->ap_rst(ap_rst);
    image_filter_Sobel_1_U0->ap_start(image_filter_Sobel_1_U0_ap_start);
    image_filter_Sobel_1_U0->ap_done(image_filter_Sobel_1_U0_ap_done);
    image_filter_Sobel_1_U0->ap_continue(image_filter_Sobel_1_U0_ap_continue);
    image_filter_Sobel_1_U0->ap_idle(image_filter_Sobel_1_U0_ap_idle);
    image_filter_Sobel_1_U0->ap_ready(image_filter_Sobel_1_U0_ap_ready);
    image_filter_Sobel_1_U0->rows(image_filter_Sobel_1_U0_rows);
    image_filter_Sobel_1_U0->cols(image_filter_Sobel_1_U0_cols);
    image_filter_Sobel_1_U0->p_src_data_stream_V_dout(image_filter_Sobel_1_U0_p_src_data_stream_V_dout);
    image_filter_Sobel_1_U0->p_src_data_stream_V_empty_n(image_filter_Sobel_1_U0_p_src_data_stream_V_empty_n);
    image_filter_Sobel_1_U0->p_src_data_stream_V_read(image_filter_Sobel_1_U0_p_src_data_stream_V_read);
    image_filter_Sobel_1_U0->p_dst_data_stream_V_din(image_filter_Sobel_1_U0_p_dst_data_stream_V_din);
    image_filter_Sobel_1_U0->p_dst_data_stream_V_full_n(image_filter_Sobel_1_U0_p_dst_data_stream_V_full_n);
    image_filter_Sobel_1_U0->p_dst_data_stream_V_write(image_filter_Sobel_1_U0_p_dst_data_stream_V_write);
    image_filter_Mat2AXIvideo_U0 = new image_filter_Mat2AXIvideo("image_filter_Mat2AXIvideo_U0");
    image_filter_Mat2AXIvideo_U0->ap_clk(ap_clk);
    image_filter_Mat2AXIvideo_U0->ap_rst(ap_rst);
    image_filter_Mat2AXIvideo_U0->ap_start(image_filter_Mat2AXIvideo_U0_ap_start);
    image_filter_Mat2AXIvideo_U0->ap_done(image_filter_Mat2AXIvideo_U0_ap_done);
    image_filter_Mat2AXIvideo_U0->ap_continue(image_filter_Mat2AXIvideo_U0_ap_continue);
    image_filter_Mat2AXIvideo_U0->ap_idle(image_filter_Mat2AXIvideo_U0_ap_idle);
    image_filter_Mat2AXIvideo_U0->ap_ready(image_filter_Mat2AXIvideo_U0_ap_ready);
    image_filter_Mat2AXIvideo_U0->rows(image_filter_Mat2AXIvideo_U0_rows);
    image_filter_Mat2AXIvideo_U0->cols(image_filter_Mat2AXIvideo_U0_cols);
    image_filter_Mat2AXIvideo_U0->img_data_stream_V_dout(image_filter_Mat2AXIvideo_U0_img_data_stream_V_dout);
    image_filter_Mat2AXIvideo_U0->img_data_stream_V_empty_n(image_filter_Mat2AXIvideo_U0_img_data_stream_V_empty_n);
    image_filter_Mat2AXIvideo_U0->img_data_stream_V_read(image_filter_Mat2AXIvideo_U0_img_data_stream_V_read);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_data_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_data_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_data_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_keep_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_keep_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_keep_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_strb_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_strb_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_strb_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_user_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_user_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_user_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_last_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_last_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_last_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_id_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_id_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_id_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_dest_V_din(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_dest_V_full_n(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_full_n);
    image_filter_Mat2AXIvideo_U0->AXI_video_strm_V_dest_V_write(image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write);
    img_0_data_stream_0_V_U = new FIFO_image_filter_img_0_data_stream_0_V("img_0_data_stream_0_V_U");
    img_0_data_stream_0_V_U->clk(ap_clk);
    img_0_data_stream_0_V_U->reset(ap_rst);
    img_0_data_stream_0_V_U->if_read_ce(img_0_data_stream_0_V_U_ap_dummy_ce);
    img_0_data_stream_0_V_U->if_write_ce(img_0_data_stream_0_V_U_ap_dummy_ce);
    img_0_data_stream_0_V_U->if_din(img_0_data_stream_0_V_din);
    img_0_data_stream_0_V_U->if_full_n(img_0_data_stream_0_V_full_n);
    img_0_data_stream_0_V_U->if_write(img_0_data_stream_0_V_write);
    img_0_data_stream_0_V_U->if_dout(img_0_data_stream_0_V_dout);
    img_0_data_stream_0_V_U->if_empty_n(img_0_data_stream_0_V_empty_n);
    img_0_data_stream_0_V_U->if_read(img_0_data_stream_0_V_read);
    img_1_data_stream_0_V_U = new FIFO_image_filter_img_1_data_stream_0_V("img_1_data_stream_0_V_U");
    img_1_data_stream_0_V_U->clk(ap_clk);
    img_1_data_stream_0_V_U->reset(ap_rst);
    img_1_data_stream_0_V_U->if_read_ce(img_1_data_stream_0_V_U_ap_dummy_ce);
    img_1_data_stream_0_V_U->if_write_ce(img_1_data_stream_0_V_U_ap_dummy_ce);
    img_1_data_stream_0_V_U->if_din(img_1_data_stream_0_V_din);
    img_1_data_stream_0_V_U->if_full_n(img_1_data_stream_0_V_full_n);
    img_1_data_stream_0_V_U->if_write(img_1_data_stream_0_V_write);
    img_1_data_stream_0_V_U->if_dout(img_1_data_stream_0_V_dout);
    img_1_data_stream_0_V_U->if_empty_n(img_1_data_stream_0_V_empty_n);
    img_1_data_stream_0_V_U->if_read(img_1_data_stream_0_V_read);
    img_2_data_stream_0_V_U = new FIFO_image_filter_img_2_data_stream_0_V("img_2_data_stream_0_V_U");
    img_2_data_stream_0_V_U->clk(ap_clk);
    img_2_data_stream_0_V_U->reset(ap_rst);
    img_2_data_stream_0_V_U->if_read_ce(img_2_data_stream_0_V_U_ap_dummy_ce);
    img_2_data_stream_0_V_U->if_write_ce(img_2_data_stream_0_V_U_ap_dummy_ce);
    img_2_data_stream_0_V_U->if_din(img_2_data_stream_0_V_din);
    img_2_data_stream_0_V_U->if_full_n(img_2_data_stream_0_V_full_n);
    img_2_data_stream_0_V_U->if_write(img_2_data_stream_0_V_write);
    img_2_data_stream_0_V_U->if_dout(img_2_data_stream_0_V_dout);
    img_2_data_stream_0_V_U->if_empty_n(img_2_data_stream_0_V_empty_n);
    img_2_data_stream_0_V_U->if_read(img_2_data_stream_0_V_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_idle );
    sensitive << ( image_filter_Sobel_U0_ap_idle );
    sensitive << ( image_filter_Sobel_1_U0_ap_idle );
    sensitive << ( image_filter_Mat2AXIvideo_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_top_allready );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( image_filter_Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_sig_top_allready);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_dout);
    sensitive << ( input_V_data_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_empty_n);
    sensitive << ( input_V_data_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_dout);
    sensitive << ( input_V_dest_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_empty_n);
    sensitive << ( input_V_dest_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_dout);
    sensitive << ( input_V_id_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_empty_n);
    sensitive << ( input_V_id_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_dout);
    sensitive << ( input_V_keep_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_empty_n);
    sensitive << ( input_V_keep_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_dout);
    sensitive << ( input_V_last_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_empty_n);
    sensitive << ( input_V_last_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_dout);
    sensitive << ( input_V_strb_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_empty_n);
    sensitive << ( input_V_strb_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_dout);
    sensitive << ( input_V_user_V_dout );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_empty_n);
    sensitive << ( input_V_user_V_empty_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_img_data_stream_V_full_n);
    sensitive << ( img_0_data_stream_0_V_full_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_full_n);
    sensitive << ( output_V_data_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_full_n);
    sensitive << ( output_V_dest_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_full_n);
    sensitive << ( output_V_id_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_full_n);
    sensitive << ( output_V_keep_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_full_n);
    sensitive << ( output_V_last_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_full_n);
    sensitive << ( output_V_strb_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_full_n);
    sensitive << ( output_V_user_V_full_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_ap_continue);
    sensitive << ( ap_sig_hs_continue );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_img_data_stream_V_dout);
    sensitive << ( img_2_data_stream_0_V_dout );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_img_data_stream_V_empty_n);
    sensitive << ( img_2_data_stream_0_V_empty_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Sobel_1_U0_ap_continue);

    SC_METHOD(thread_image_filter_Sobel_1_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Sobel_1_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Sobel_1_U0_p_dst_data_stream_V_full_n);
    sensitive << ( img_2_data_stream_0_V_full_n );

    SC_METHOD(thread_image_filter_Sobel_1_U0_p_src_data_stream_V_dout);
    sensitive << ( img_1_data_stream_0_V_dout );

    SC_METHOD(thread_image_filter_Sobel_1_U0_p_src_data_stream_V_empty_n);
    sensitive << ( img_1_data_stream_0_V_empty_n );

    SC_METHOD(thread_image_filter_Sobel_1_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Sobel_U0_ap_continue);

    SC_METHOD(thread_image_filter_Sobel_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Sobel_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Sobel_U0_p_dst_data_stream_V_full_n);
    sensitive << ( img_1_data_stream_0_V_full_n );

    SC_METHOD(thread_image_filter_Sobel_U0_p_src_data_stream_V_dout);
    sensitive << ( img_0_data_stream_0_V_dout );

    SC_METHOD(thread_image_filter_Sobel_U0_p_src_data_stream_V_empty_n);
    sensitive << ( img_0_data_stream_0_V_empty_n );

    SC_METHOD(thread_image_filter_Sobel_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_img_0_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_data_stream_0_V_din);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_V_din );

    SC_METHOD(thread_img_0_data_stream_0_V_read);
    sensitive << ( image_filter_Sobel_U0_p_src_data_stream_V_read );

    SC_METHOD(thread_img_0_data_stream_0_V_write);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_V_write );

    SC_METHOD(thread_img_1_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_1_data_stream_0_V_din);
    sensitive << ( image_filter_Sobel_U0_p_dst_data_stream_V_din );

    SC_METHOD(thread_img_1_data_stream_0_V_read);
    sensitive << ( image_filter_Sobel_1_U0_p_src_data_stream_V_read );

    SC_METHOD(thread_img_1_data_stream_0_V_write);
    sensitive << ( image_filter_Sobel_U0_p_dst_data_stream_V_write );

    SC_METHOD(thread_img_2_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_2_data_stream_0_V_din);
    sensitive << ( image_filter_Sobel_1_U0_p_dst_data_stream_V_din );

    SC_METHOD(thread_img_2_data_stream_0_V_read);
    sensitive << ( image_filter_Mat2AXIvideo_U0_img_data_stream_V_read );

    SC_METHOD(thread_img_2_data_stream_0_V_write);
    sensitive << ( image_filter_Sobel_1_U0_p_dst_data_stream_V_write );

    SC_METHOD(thread_input_V_data_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read );

    SC_METHOD(thread_input_V_dest_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read );

    SC_METHOD(thread_input_V_id_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read );

    SC_METHOD(thread_input_V_keep_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read );

    SC_METHOD(thread_input_V_last_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read );

    SC_METHOD(thread_input_V_strb_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read );

    SC_METHOD(thread_input_V_user_V_read);
    sensitive << ( image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read );

    SC_METHOD(thread_output_V_data_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din );

    SC_METHOD(thread_output_V_data_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write );

    SC_METHOD(thread_output_V_dest_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din );

    SC_METHOD(thread_output_V_dest_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write );

    SC_METHOD(thread_output_V_id_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din );

    SC_METHOD(thread_output_V_id_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write );

    SC_METHOD(thread_output_V_keep_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din );

    SC_METHOD(thread_output_V_keep_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write );

    SC_METHOD(thread_output_V_last_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din );

    SC_METHOD(thread_output_V_last_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write );

    SC_METHOD(thread_output_V_strb_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din );

    SC_METHOD(thread_output_V_strb_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write );

    SC_METHOD(thread_output_V_user_V_din);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din );

    SC_METHOD(thread_output_V_user_V_write);
    sensitive << ( image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = SC_LOGIC_0;
    ap_reg_procdone_image_filter_Sobel_U0 = SC_LOGIC_0;
    ap_reg_procdone_image_filter_Sobel_1_U0 = SC_LOGIC_0;
    ap_reg_procdone_image_filter_Mat2AXIvideo_U0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, input_V_data_V_dout, "(port)input_V_data_V_dout");
    sc_trace(mVcdFile, input_V_data_V_empty_n, "(port)input_V_data_V_empty_n");
    sc_trace(mVcdFile, input_V_data_V_read, "(port)input_V_data_V_read");
    sc_trace(mVcdFile, input_V_keep_V_dout, "(port)input_V_keep_V_dout");
    sc_trace(mVcdFile, input_V_keep_V_empty_n, "(port)input_V_keep_V_empty_n");
    sc_trace(mVcdFile, input_V_keep_V_read, "(port)input_V_keep_V_read");
    sc_trace(mVcdFile, input_V_strb_V_dout, "(port)input_V_strb_V_dout");
    sc_trace(mVcdFile, input_V_strb_V_empty_n, "(port)input_V_strb_V_empty_n");
    sc_trace(mVcdFile, input_V_strb_V_read, "(port)input_V_strb_V_read");
    sc_trace(mVcdFile, input_V_user_V_dout, "(port)input_V_user_V_dout");
    sc_trace(mVcdFile, input_V_user_V_empty_n, "(port)input_V_user_V_empty_n");
    sc_trace(mVcdFile, input_V_user_V_read, "(port)input_V_user_V_read");
    sc_trace(mVcdFile, input_V_last_V_dout, "(port)input_V_last_V_dout");
    sc_trace(mVcdFile, input_V_last_V_empty_n, "(port)input_V_last_V_empty_n");
    sc_trace(mVcdFile, input_V_last_V_read, "(port)input_V_last_V_read");
    sc_trace(mVcdFile, input_V_id_V_dout, "(port)input_V_id_V_dout");
    sc_trace(mVcdFile, input_V_id_V_empty_n, "(port)input_V_id_V_empty_n");
    sc_trace(mVcdFile, input_V_id_V_read, "(port)input_V_id_V_read");
    sc_trace(mVcdFile, input_V_dest_V_dout, "(port)input_V_dest_V_dout");
    sc_trace(mVcdFile, input_V_dest_V_empty_n, "(port)input_V_dest_V_empty_n");
    sc_trace(mVcdFile, input_V_dest_V_read, "(port)input_V_dest_V_read");
    sc_trace(mVcdFile, output_V_data_V_din, "(port)output_V_data_V_din");
    sc_trace(mVcdFile, output_V_data_V_full_n, "(port)output_V_data_V_full_n");
    sc_trace(mVcdFile, output_V_data_V_write, "(port)output_V_data_V_write");
    sc_trace(mVcdFile, output_V_keep_V_din, "(port)output_V_keep_V_din");
    sc_trace(mVcdFile, output_V_keep_V_full_n, "(port)output_V_keep_V_full_n");
    sc_trace(mVcdFile, output_V_keep_V_write, "(port)output_V_keep_V_write");
    sc_trace(mVcdFile, output_V_strb_V_din, "(port)output_V_strb_V_din");
    sc_trace(mVcdFile, output_V_strb_V_full_n, "(port)output_V_strb_V_full_n");
    sc_trace(mVcdFile, output_V_strb_V_write, "(port)output_V_strb_V_write");
    sc_trace(mVcdFile, output_V_user_V_din, "(port)output_V_user_V_din");
    sc_trace(mVcdFile, output_V_user_V_full_n, "(port)output_V_user_V_full_n");
    sc_trace(mVcdFile, output_V_user_V_write, "(port)output_V_user_V_write");
    sc_trace(mVcdFile, output_V_last_V_din, "(port)output_V_last_V_din");
    sc_trace(mVcdFile, output_V_last_V_full_n, "(port)output_V_last_V_full_n");
    sc_trace(mVcdFile, output_V_last_V_write, "(port)output_V_last_V_write");
    sc_trace(mVcdFile, output_V_id_V_din, "(port)output_V_id_V_din");
    sc_trace(mVcdFile, output_V_id_V_full_n, "(port)output_V_id_V_full_n");
    sc_trace(mVcdFile, output_V_id_V_write, "(port)output_V_id_V_write");
    sc_trace(mVcdFile, output_V_dest_V_din, "(port)output_V_dest_V_din");
    sc_trace(mVcdFile, output_V_dest_V_full_n, "(port)output_V_dest_V_full_n");
    sc_trace(mVcdFile, output_V_dest_V_write, "(port)output_V_dest_V_write");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_start, "image_filter_AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_done, "image_filter_AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_continue, "image_filter_AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_idle, "image_filter_AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_ready, "image_filter_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_dout, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_dout");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_empty_n, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_empty_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read, "image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_rows, "image_filter_AXIvideo2Mat_U0_rows");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_cols, "image_filter_AXIvideo2Mat_U0_cols");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_V_din, "image_filter_AXIvideo2Mat_U0_img_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_V_full_n, "image_filter_AXIvideo2Mat_U0_img_data_stream_V_full_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_V_write, "image_filter_AXIvideo2Mat_U0_img_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Sobel_U0_ap_start, "image_filter_Sobel_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Sobel_U0_ap_done, "image_filter_Sobel_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Sobel_U0_ap_continue, "image_filter_Sobel_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Sobel_U0_ap_idle, "image_filter_Sobel_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Sobel_U0_ap_ready, "image_filter_Sobel_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Sobel_U0_rows, "image_filter_Sobel_U0_rows");
    sc_trace(mVcdFile, image_filter_Sobel_U0_cols, "image_filter_Sobel_U0_cols");
    sc_trace(mVcdFile, image_filter_Sobel_U0_p_src_data_stream_V_dout, "image_filter_Sobel_U0_p_src_data_stream_V_dout");
    sc_trace(mVcdFile, image_filter_Sobel_U0_p_src_data_stream_V_empty_n, "image_filter_Sobel_U0_p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, image_filter_Sobel_U0_p_src_data_stream_V_read, "image_filter_Sobel_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_Sobel_U0_p_dst_data_stream_V_din, "image_filter_Sobel_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_Sobel_U0_p_dst_data_stream_V_full_n, "image_filter_Sobel_U0_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, image_filter_Sobel_U0_p_dst_data_stream_V_write, "image_filter_Sobel_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_ap_start, "image_filter_Sobel_1_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_ap_done, "image_filter_Sobel_1_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_ap_continue, "image_filter_Sobel_1_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_ap_idle, "image_filter_Sobel_1_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_ap_ready, "image_filter_Sobel_1_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_rows, "image_filter_Sobel_1_U0_rows");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_cols, "image_filter_Sobel_1_U0_cols");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_p_src_data_stream_V_dout, "image_filter_Sobel_1_U0_p_src_data_stream_V_dout");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_p_src_data_stream_V_empty_n, "image_filter_Sobel_1_U0_p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_p_src_data_stream_V_read, "image_filter_Sobel_1_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_p_dst_data_stream_V_din, "image_filter_Sobel_1_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_p_dst_data_stream_V_full_n, "image_filter_Sobel_1_U0_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, image_filter_Sobel_1_U0_p_dst_data_stream_V_write, "image_filter_Sobel_1_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_start, "image_filter_Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_done, "image_filter_Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_continue, "image_filter_Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_idle, "image_filter_Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_ready, "image_filter_Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_rows, "image_filter_Mat2AXIvideo_U0_rows");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_cols, "image_filter_Mat2AXIvideo_U0_cols");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_img_data_stream_V_dout, "image_filter_Mat2AXIvideo_U0_img_data_stream_V_dout");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_img_data_stream_V_empty_n, "image_filter_Mat2AXIvideo_U0_img_data_stream_V_empty_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_img_data_stream_V_read, "image_filter_Mat2AXIvideo_U0_img_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_full_n, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_full_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write, "image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, img_0_data_stream_0_V_U_ap_dummy_ce, "img_0_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_data_stream_0_V_din, "img_0_data_stream_0_V_din");
    sc_trace(mVcdFile, img_0_data_stream_0_V_full_n, "img_0_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_write, "img_0_data_stream_0_V_write");
    sc_trace(mVcdFile, img_0_data_stream_0_V_dout, "img_0_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_V_empty_n, "img_0_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_read, "img_0_data_stream_0_V_read");
    sc_trace(mVcdFile, img_1_data_stream_0_V_U_ap_dummy_ce, "img_1_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_1_data_stream_0_V_din, "img_1_data_stream_0_V_din");
    sc_trace(mVcdFile, img_1_data_stream_0_V_full_n, "img_1_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_write, "img_1_data_stream_0_V_write");
    sc_trace(mVcdFile, img_1_data_stream_0_V_dout, "img_1_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_V_empty_n, "img_1_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_read, "img_1_data_stream_0_V_read");
    sc_trace(mVcdFile, img_2_data_stream_0_V_U_ap_dummy_ce, "img_2_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_2_data_stream_0_V_din, "img_2_data_stream_0_V_din");
    sc_trace(mVcdFile, img_2_data_stream_0_V_full_n, "img_2_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_2_data_stream_0_V_write, "img_2_data_stream_0_V_write");
    sc_trace(mVcdFile, img_2_data_stream_0_V_dout, "img_2_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_2_data_stream_0_V_empty_n, "img_2_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_0_V_read, "img_2_data_stream_0_V_read");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_AXIvideo2Mat_U0, "ap_reg_procdone_image_filter_AXIvideo2Mat_U0");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_Sobel_U0, "ap_reg_procdone_image_filter_Sobel_U0");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_Sobel_1_U0, "ap_reg_procdone_image_filter_Sobel_1_U0");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_Mat2AXIvideo_U0, "ap_reg_procdone_image_filter_Mat2AXIvideo_U0");
    sc_trace(mVcdFile, ap_CS, "ap_CS");
    sc_trace(mVcdFile, ap_sig_top_allready, "ap_sig_top_allready");
#endif

    }
    mHdltvinHandle.open("image_filter.hdltvin.dat");
    mHdltvoutHandle.open("image_filter.hdltvout.dat");
}

image_filter::~image_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete image_filter_AXIvideo2Mat_U0;
    delete image_filter_Sobel_U0;
    delete image_filter_Sobel_1_U0;
    delete image_filter_Mat2AXIvideo_U0;
    delete img_0_data_stream_0_V_U;
    delete img_1_data_stream_0_V_U;
    delete img_2_data_stream_0_V_U;
}

void image_filter::thread_ap_clk_no_reset_() {
    ap_CS = ap_const_logic_0;
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(image_filter_AXIvideo2Mat_U0_ap_done.read(), ap_const_logic_1)) {
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_Mat2AXIvideo_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_Mat2AXIvideo_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_U0_ap_done.read())) {
            ap_reg_procdone_image_filter_Mat2AXIvideo_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_Sobel_1_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_Sobel_1_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Sobel_1_U0_ap_done.read())) {
            ap_reg_procdone_image_filter_Sobel_1_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_Sobel_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_Sobel_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Sobel_U0_ap_done.read())) {
            ap_reg_procdone_image_filter_Sobel_U0 = ap_const_logic_1;
        }
    }
}

void image_filter::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void image_filter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(image_filter_AXIvideo2Mat_U0_ap_idle.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Sobel_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Sobel_1_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_U0_ap_idle.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter::thread_ap_ready() {
    ap_ready = ap_sig_top_allready.read();
}

void image_filter::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void image_filter::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void image_filter::thread_ap_sig_top_allready() {
    ap_sig_top_allready = image_filter_AXIvideo2Mat_U0_ap_ready.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_dout = input_V_data_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_empty_n = input_V_data_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_dout = input_V_dest_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_empty_n = input_V_dest_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_dout = input_V_id_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_empty_n = input_V_id_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_dout = input_V_keep_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_empty_n = input_V_keep_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_dout = input_V_last_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_empty_n = input_V_last_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_dout = input_V_strb_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_empty_n = input_V_strb_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_dout() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_dout = input_V_user_V_dout.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_empty_n() {
    image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_empty_n = input_V_user_V_empty_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_ap_continue() {
    image_filter_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_ap_start() {
    image_filter_AXIvideo2Mat_U0_ap_start = (ap_start.read());
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_cols() {
    image_filter_AXIvideo2Mat_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_img_data_stream_V_full_n() {
    image_filter_AXIvideo2Mat_U0_img_data_stream_V_full_n = img_0_data_stream_0_V_full_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_rows() {
    image_filter_AXIvideo2Mat_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_full_n = output_V_data_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_full_n = output_V_dest_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_full_n = output_V_id_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_full_n = output_V_keep_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_full_n = output_V_last_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_full_n = output_V_strb_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_full_n() {
    image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_full_n = output_V_user_V_full_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_ap_continue() {
    image_filter_Mat2AXIvideo_U0_ap_continue = ap_sig_hs_continue.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_ap_start() {
    image_filter_Mat2AXIvideo_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_cols() {
    image_filter_Mat2AXIvideo_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_img_data_stream_V_dout() {
    image_filter_Mat2AXIvideo_U0_img_data_stream_V_dout = img_2_data_stream_0_V_dout.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_img_data_stream_V_empty_n() {
    image_filter_Mat2AXIvideo_U0_img_data_stream_V_empty_n = img_2_data_stream_0_V_empty_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_rows() {
    image_filter_Mat2AXIvideo_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Sobel_1_U0_ap_continue() {
    image_filter_Sobel_1_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Sobel_1_U0_ap_start() {
    image_filter_Sobel_1_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Sobel_1_U0_cols() {
    image_filter_Sobel_1_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Sobel_1_U0_p_dst_data_stream_V_full_n() {
    image_filter_Sobel_1_U0_p_dst_data_stream_V_full_n = img_2_data_stream_0_V_full_n.read();
}

void image_filter::thread_image_filter_Sobel_1_U0_p_src_data_stream_V_dout() {
    image_filter_Sobel_1_U0_p_src_data_stream_V_dout = img_1_data_stream_0_V_dout.read();
}

void image_filter::thread_image_filter_Sobel_1_U0_p_src_data_stream_V_empty_n() {
    image_filter_Sobel_1_U0_p_src_data_stream_V_empty_n = img_1_data_stream_0_V_empty_n.read();
}

void image_filter::thread_image_filter_Sobel_1_U0_rows() {
    image_filter_Sobel_1_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Sobel_U0_ap_continue() {
    image_filter_Sobel_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Sobel_U0_ap_start() {
    image_filter_Sobel_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Sobel_U0_cols() {
    image_filter_Sobel_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Sobel_U0_p_dst_data_stream_V_full_n() {
    image_filter_Sobel_U0_p_dst_data_stream_V_full_n = img_1_data_stream_0_V_full_n.read();
}

void image_filter::thread_image_filter_Sobel_U0_p_src_data_stream_V_dout() {
    image_filter_Sobel_U0_p_src_data_stream_V_dout = img_0_data_stream_0_V_dout.read();
}

void image_filter::thread_image_filter_Sobel_U0_p_src_data_stream_V_empty_n() {
    image_filter_Sobel_U0_p_src_data_stream_V_empty_n = img_0_data_stream_0_V_empty_n.read();
}

void image_filter::thread_image_filter_Sobel_U0_rows() {
    image_filter_Sobel_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_img_0_data_stream_0_V_U_ap_dummy_ce() {
    img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_0_data_stream_0_V_din() {
    img_0_data_stream_0_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_V_din.read();
}

void image_filter::thread_img_0_data_stream_0_V_read() {
    img_0_data_stream_0_V_read = image_filter_Sobel_U0_p_src_data_stream_V_read.read();
}

void image_filter::thread_img_0_data_stream_0_V_write() {
    img_0_data_stream_0_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_V_write.read();
}

void image_filter::thread_img_1_data_stream_0_V_U_ap_dummy_ce() {
    img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_1_data_stream_0_V_din() {
    img_1_data_stream_0_V_din = image_filter_Sobel_U0_p_dst_data_stream_V_din.read();
}

void image_filter::thread_img_1_data_stream_0_V_read() {
    img_1_data_stream_0_V_read = image_filter_Sobel_1_U0_p_src_data_stream_V_read.read();
}

void image_filter::thread_img_1_data_stream_0_V_write() {
    img_1_data_stream_0_V_write = image_filter_Sobel_U0_p_dst_data_stream_V_write.read();
}

void image_filter::thread_img_2_data_stream_0_V_U_ap_dummy_ce() {
    img_2_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_2_data_stream_0_V_din() {
    img_2_data_stream_0_V_din = image_filter_Sobel_1_U0_p_dst_data_stream_V_din.read();
}

void image_filter::thread_img_2_data_stream_0_V_read() {
    img_2_data_stream_0_V_read = image_filter_Mat2AXIvideo_U0_img_data_stream_V_read.read();
}

void image_filter::thread_img_2_data_stream_0_V_write() {
    img_2_data_stream_0_V_write = image_filter_Sobel_1_U0_p_dst_data_stream_V_write.read();
}

void image_filter::thread_input_V_data_V_read() {
    input_V_data_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read.read();
}

void image_filter::thread_input_V_dest_V_read() {
    input_V_dest_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read.read();
}

void image_filter::thread_input_V_id_V_read() {
    input_V_id_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read.read();
}

void image_filter::thread_input_V_keep_V_read() {
    input_V_keep_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read.read();
}

void image_filter::thread_input_V_last_V_read() {
    input_V_last_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read.read();
}

void image_filter::thread_input_V_strb_V_read() {
    input_V_strb_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read.read();
}

void image_filter::thread_input_V_user_V_read() {
    input_V_user_V_read = image_filter_AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read.read();
}

void image_filter::thread_output_V_data_V_din() {
    output_V_data_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din.read();
}

void image_filter::thread_output_V_data_V_write() {
    output_V_data_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write.read();
}

void image_filter::thread_output_V_dest_V_din() {
    output_V_dest_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din.read();
}

void image_filter::thread_output_V_dest_V_write() {
    output_V_dest_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write.read();
}

void image_filter::thread_output_V_id_V_din() {
    output_V_id_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din.read();
}

void image_filter::thread_output_V_id_V_write() {
    output_V_id_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write.read();
}

void image_filter::thread_output_V_keep_V_din() {
    output_V_keep_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din.read();
}

void image_filter::thread_output_V_keep_V_write() {
    output_V_keep_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write.read();
}

void image_filter::thread_output_V_last_V_din() {
    output_V_last_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din.read();
}

void image_filter::thread_output_V_last_V_write() {
    output_V_last_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write.read();
}

void image_filter::thread_output_V_strb_V_din() {
    output_V_strb_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din.read();
}

void image_filter::thread_output_V_strb_V_write() {
    output_V_strb_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write.read();
}

void image_filter::thread_output_V_user_V_din() {
    output_V_user_V_din = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din.read();
}

void image_filter::thread_output_V_user_V_write() {
    output_V_user_V_write = image_filter_Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write.read();
}

void image_filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"input_V_data_V_dout\" :  \"" << input_V_data_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_data_V_empty_n\" :  \"" << input_V_data_V_empty_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"input_V_data_V_read\" :  \"" << input_V_data_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_keep_V_dout\" :  \"" << input_V_keep_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_keep_V_empty_n\" :  \"" << input_V_keep_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_keep_V_read\" :  \"" << input_V_keep_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_strb_V_dout\" :  \"" << input_V_strb_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_strb_V_empty_n\" :  \"" << input_V_strb_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_strb_V_read\" :  \"" << input_V_strb_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_user_V_dout\" :  \"" << input_V_user_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_user_V_empty_n\" :  \"" << input_V_user_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_user_V_read\" :  \"" << input_V_user_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_last_V_dout\" :  \"" << input_V_last_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_last_V_empty_n\" :  \"" << input_V_last_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_last_V_read\" :  \"" << input_V_last_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_id_V_dout\" :  \"" << input_V_id_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_id_V_empty_n\" :  \"" << input_V_id_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_id_V_read\" :  \"" << input_V_id_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_dest_V_dout\" :  \"" << input_V_dest_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_dest_V_empty_n\" :  \"" << input_V_dest_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_dest_V_read\" :  \"" << input_V_dest_V_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_data_V_din\" :  \"" << output_V_data_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_data_V_full_n\" :  \"" << output_V_data_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_data_V_write\" :  \"" << output_V_data_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_keep_V_din\" :  \"" << output_V_keep_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_keep_V_full_n\" :  \"" << output_V_keep_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_keep_V_write\" :  \"" << output_V_keep_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_strb_V_din\" :  \"" << output_V_strb_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_strb_V_full_n\" :  \"" << output_V_strb_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_strb_V_write\" :  \"" << output_V_strb_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_user_V_din\" :  \"" << output_V_user_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_user_V_full_n\" :  \"" << output_V_user_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_user_V_write\" :  \"" << output_V_user_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_last_V_din\" :  \"" << output_V_last_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_last_V_full_n\" :  \"" << output_V_last_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_last_V_write\" :  \"" << output_V_last_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_id_V_din\" :  \"" << output_V_id_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_id_V_full_n\" :  \"" << output_V_id_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_id_V_write\" :  \"" << output_V_id_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_dest_V_din\" :  \"" << output_V_dest_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_dest_V_full_n\" :  \"" << output_V_dest_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_dest_V_write\" :  \"" << output_V_dest_V_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rows\" :  \"" << rows.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"cols\" :  \"" << cols.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

